In [1]:
import pandas as pd

df = pd.DataFrame([{'Name': 'Chris', 'Item Purchased': 'Sponge', 'Cost': 22.50},
                   {'Name': 'Kevyn', 'Item Purchased': 'Kitty Litter', 'Cost': 2.50},
                   {'Name': 'Filip', 'Item Purchased': 'Spoon', 'Cost': 5.00}],
                  index=['Store 1', 'Store 1', 'Store 2'])
df

         Cost Item Purchased   Name
Store 1  22.5         Sponge  Chris
Store 1   2.5   Kitty Litter  Kevyn
Store 2   5.0          Spoon  Filip

In [2]:
df['Date'] = ['December 1','January 1', 'mid-may']
df

         Cost Item Purchased   Name        Date
Store 1  22.5         Sponge  Chris  December 1
Store 1   2.5   Kitty Litter  Kevyn   January 1
Store 2   5.0          Spoon  Filip     mid-may

In [3]:
df['Name'] = df['Name'].replace('Chris','vis')

In [4]:
df

         Cost Item Purchased   Name        Date
Store 1  22.5         Sponge    vis  December 1
Store 1   2.5   Kitty Litter  Kevyn   January 1
Store 2   5.0          Spoon  Filip     mid-may

In [5]:
df['Delivered'] = True
df

         Cost Item Purchased   Name        Date  Delivered
Store 1  22.5         Sponge  Chris  December 1       True
Store 1   2.5   Kitty Litter  Kevyn   January 1       True
Store 2   5.0          Spoon  Filip     mid-may       True

In [7]:
df['Feedback'] = ['Positive',None,'Negative']
df

         Cost Item Purchased   Name        Date  Delivered  Feedback
Store 1  22.5         Sponge  Chris  December 1       True  Positive
Store 1   2.5   Kitty Litter  Kevyn   January 1       True      None
Store 2   5.0          Spoon  Filip     mid-may       True  Negative

In [8]:
adf = df.reset_index()

In [9]:
adf

     index  Cost Item Purchased   Name        Date  Delivered  Feedback
0  Store 1  22.5         Sponge  Chris  December 1       True  Positive
1  Store 1   2.5   Kitty Litter  Kevyn   January 1       True      None
2  Store 2   5.0          Spoon  Filip     mid-may       True  Negative

In [10]:
adf['Date'] = pd.Series({0:'December 1',1:'mid-may'})
adf

     index  Cost Item Purchased   Name        Date  Delivered  Feedback
0  Store 1  22.5         Sponge  Chris  December 1       True  Positive
1  Store 1   2.5   Kitty Litter  Kevyn     mid-may       True      None
2  Store 2   5.0          Spoon  Filip         NaN       True  Negative

In [11]:
staff_df = pd.DataFrame([{'Name': 'Kelly', 'Role': 'Director of HR'},
                         {'Name': 'Sally', 'Role': 'Course liasion'},
                         {'Name': 'James', 'Role': 'Grader'}])
staff_df = staff_df.set_index('Name')
student_df = pd.DataFrame([{'Name': 'James', 'School': 'Business'},
                           {'Name': 'Mike', 'School': 'Law'},
                           {'Name': 'Sally', 'School': 'Engineering'}])
student_df = student_df.set_index('Name')
print(staff_df.head())
print()
print(student_df.head())

                 Role
Name
Kelly  Director of HR
Sally  Course liasion
James          Grader

            School
Name
James     Business
Mike           Law
Sally  Engineering

In [12]:
pd.merge(staff_df,student_df,how ='outer',left_index = True, right_index=True)

                 Role       School
Name
James          Grader     Business
Kelly  Director of HR          NaN
Mike              NaN          Law
Sally  Course liasion  Engineering

In [13]:
pd.merge(staff_df,student_df,how = 'inner',left_index=True,right_index=True)

                 Role       School
Name
Sally  Course liasion  Engineering
James          Grader     Business

In [18]:
pd.merge(staff_df,student_df,how = 'left',left_index=True,right_index=True)

                 Role       School
Name
Kelly  Director of HR          NaN
Sally  Course liasion  Engineering
James          Grader     Business

In [19]:
pd.merge(staff_df,student_df,how = 'right',left_index =True,right_index = True)

                 Role       School
Name
James          Grader     Business
Mike              NaN          Law
Sally  Course liasion  Engineering

In [20]:
staff_df = staff_df.reset_index()
student_df = student_df.reset_index()
print(staff_df)
print()
print(student_df)

    Name            Role
0  Kelly  Director of HR
1  Sally  Course liasion
2  James          Grader

    Name       School
0  James     Business
1   Mike          Law
2  Sally  Engineering

In [22]:
pd.merge(staff_df,student_df,how = 'left',left_on='Name',right_on='Name')

    Name            Role       School
0  Kelly  Director of HR          NaN
1  Sally  Course liasion  Engineering
2  James          Grader     Business

In [23]:
pd.merge(staff_df,student_df,how = 'right',left_on='Name',right_on = 'Name')

    Name            Role       School
0  Sally  Course liasion  Engineering
1  James          Grader     Business
2   Mike             NaN          Law

In [24]:
staff_df = pd.DataFrame([{'Name': 'Kelly', 'Role': 'Director of HR', 'Location': 'State Street'},
                         {'Name': 'Sally', 'Role': 'Course liasion', 'Location': 'Washington Avenue'},
                         {'Name': 'James', 'Role': 'Grader', 'Location': 'Washington Avenue'}])
student_df = pd.DataFrame([{'Name': 'James', 'School': 'Business', 'Location': '1024 Billiard Avenue'},
                           {'Name': 'Mike', 'School': 'Law', 'Location': 'Fraternity House #22'},
                           {'Name': 'Sally', 'School': 'Engineering', 'Location': '512 Wilson Crescent'}])
pd.merge(staff_df, student_df, how='left', left_on='Name', right_on='Name')

          Location_x   Name            Role            Location_y       School
0       State Street  Kelly  Director of HR                   NaN          NaN
1  Washington Avenue  Sally  Course liasion   512 Wilson Crescent  Engineering
2  Washington Avenue  James          Grader  1024 Billiard Avenue     Business

In [28]:
products = pd.DataFrame([{'Product ID':4109,'Price':5.0,'Product':'Sushi Roll'},
                         {'Product ID':1412,'Price':0.5,'Product':'Egg'},
                         {'Product ID':8931,'Price':1.5,'Product':'Bagel'}])
products = products.set_index('Product ID')

In [29]:
products

            Price     Product
Product ID
4109          5.0  Sushi Roll
1412          0.5         Egg
8931          1.5       Bagel

In [30]:
invoices = pd.DataFrame([{'Customer':'Ali','Product ID':4109,'Quantity':1},
                         {'Customer':'Eric','Product ID':1412,'Quantity':12},
                         {'Customer':'Ande','Product ID':8931,'Quantity':6},
                         {'Customer':'Sam','Product ID':4109,'Quantity':2}])
invoices

  Customer  Product ID  Quantity
0      Ali        4109         1
1     Eric        1412        12
2     Ande        8931         6
3      Sam        4109         2

In [36]:
pd.merge(products,invoices,how = 'outer',left_index = True,right_on ='Product ID')

   Price     Product Customer  Product ID  Quantity
0    5.0  Sushi Roll      Ali        4109         1
3    5.0  Sushi Roll      Sam        4109         2
1    0.5         Egg     Eric        1412        12
2    1.5       Bagel     Ande        8931         6

In [31]:
invoi = invoices.set_index('Product ID')

In [32]:
invoi

           Customer  Quantity
Product ID
4109            Ali         1
1412           Eric        12
8931           Ande         6
4109            Sam         2

In [37]:
a =pd.merge(products,invoi,how = 'outer',left_index = True,right_index =True)

In [39]:
a.reset_index()

   Product ID  Price     Product Customer  Quantity
0        1412    0.5         Egg     Eric        12
1        4109    5.0  Sushi Roll      Ali         1
2        4109    5.0  Sushi Roll      Sam         2
3        8931    1.5       Bagel     Ande         6

In [40]:
staff_df = pd.DataFrame([{'First Name': 'Kelly', 'Last Name': 'Desjardins', 'Role': 'Director of HR'},
                         {'First Name': 'Sally', 'Last Name': 'Brooks', 'Role': 'Course liasion'},
                         {'First Name': 'James', 'Last Name': 'Wilde', 'Role': 'Grader'}])
student_df = pd.DataFrame([{'First Name': 'James', 'Last Name': 'Hammond', 'School': 'Business'},
                           {'First Name': 'Mike', 'Last Name': 'Smith', 'School': 'Law'},
                           {'First Name': 'Sally', 'Last Name': 'Brooks', 'School': 'Engineering'}])
staff_df
student_df
pd.merge(staff_df, student_df, how='inner', left_on=['First Name','Last Name'], right_on=['First Name','Last Name'])

  First Name Last Name            Role       School
0      Sally    Brooks  Course liasion  Engineering

In [41]:
staff_df

  First Name   Last Name            Role
0      Kelly  Desjardins  Director of HR
1      Sally      Brooks  Course liasion
2      James       Wilde          Grader

In [42]:
student_df

  First Name Last Name       School
0      James   Hammond     Business
1       Mike     Smith          Law
2      Sally    Brooks  Engineering

In [43]:
import pandas as pd
df = pd.read_csv('census.csv')
df

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.002295,-0.193196,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861
5,50,3,6,1,9,Alabama,Blount County,57322,57322,57373,...,1.807375,-1.177622,-1.748766,-2.062535,-1.369970,1.859511,-0.848580,-1.402476,-1.577232,-0.884411
6,50,3,6,1,11,Alabama,Bullock County,10914,10915,10887,...,-30.953709,-5.180127,-1.130263,14.354290,-16.167247,-29.001673,-2.825524,1.507017,17.243790,-13.193961
7,50,3,6,1,13,Alabama,Butler County,20947,20946,20944,...,-14.032727,-11.684234,-5.655413,1.085428,-6.529805,-13.936612,-11.586865,-5.557058,1.184103,-6.430868
8,50,3,6,1,15,Alabama,Calhoun County,118572,118586,118437,...,-6.155670,-4.611706,-5.524649,-4.463211,-3.376322,-5.791579,-4.092677,-5.062836,-3.912834,-2.806406
9,50,3,6,1,17,Alabama,Chambers County,34215,34170,34098,...,-2.731639,3.849092,2.872721,-2.287222,1.349468,-1.821092,4.701181,3.781439,-1.290228,2.346901
10,50,3,6,1,19,Alabama,Cherokee County,25989,25986,25976,...,6.339327,1.113180,5.488706,-0.076806,-3.239866,6.416167,1.420264,5.757384,0.230419,-2.931307
11,50,3,6,1,21,Alabama,Chilton County,43643,43631,43665,...,-1.372935,-2.653369,0.480044,0.456017,-2.253483,-0.823761,-2.447504,0.868651,0.957636,-1.752709
12,50,3,6,1,23,Alabama,Choctaw County,13859,13858,13841,...,-15.455274,-0.737028,-8.766391,-1.274984,-5.291205,-15.528177,-0.737028,-8.766391,-1.274984,-5.291205
13,50,3,6,1,25,Alabama,Clarke County,25833,25840,25767,...,-6.194363,-17.667705,-0.318345,-8.686428,-5.613667,-6.077488,-17.509958,-0.159172,-8.486280,-5.411736
14,50,3,6,1,27,Alabama,Clay County,13932,13932,13880,...,-10.744102,-13.345130,4.902871,5.702648,3.912450,-10.816697,-13.345130,4.977157,5.776708,3.986270
15,50,3,6,1,29,Alabama,Cleburne County,14972,14972,14973,...,-3.673524,-5.151880,7.345821,3.654485,-3.123961,-3.673524,-5.151880,7.345821,3.654485,-3.123961
16,50,3,6,1,31,Alabama,Coffee County,49948,49948,50177,...,0.377640,7.675579,-13.146535,-3.602859,2.214774,2.166460,11.513368,-10.438741,-0.767822,5.350738
17,50,3,6,1,33,Alabama,Colbert County,54428,54428,54514,...,-0.073423,1.065051,1.762390,1.835688,-0.110260,0.513964,1.469035,2.276420,2.533249,0.588052
18,50,3,6,1,35,Alabama,Conecuh County,13228,13228,13208,...,-4.861559,-7.504690,-6.107224,-14.645416,2.684140,-4.861559,-7.504690,-6.107224,-14.645416,2.684140
19,50,3,6,1,37,Alabama,Coosa County,11539,11758,11758,...,-33.930581,-10.291443,-4.313831,-22.958017,-5.387581,-34.017138,-10.380162,-4.403703,-23.049483,-5.387581
20,50,3,6,1,39,Alabama,Covington County,37765,37765,37796,...,6.696899,-4.612668,0.740271,3.697932,-0.316945,6.881460,-4.559952,0.793147,3.750759,-0.264121
21,50,3,6,1,41,Alabama,Crenshaw County,13906,13906,13853,...,1.729792,3.950156,-1.864936,3.084648,3.439504,2.666763,5.099293,-0.502098,4.734577,5.087600
22,50,3,6,1,43,Alabama,Cullman County,80406,80410,80473,...,-1.404233,-1.019628,4.071247,5.087142,7.915406,-1.031427,-0.634159,4.542916,5.593387,8.417777
23,50,3,6,1,45,Alabama,Dale County,50251,50251,50358,...,-10.749798,-5.277150,-15.236079,-11.979785,-5.107706,-9.575283,-0.776637,-12.640155,-9.503292,-1.998668
24,50,3,6,1,47,Alabama,Dallas County,43820,43820,43803,...,-15.635599,-11.308243,-16.745678,-9.344789,-14.687232,-15.727573,-11.378047,-16.792849,-9.368689,-14.711389
25,50,3,6,1,49,Alabama,DeKalb County,71109,71115,71142,...,0.294677,-9.302391,-1.748807,0.267830,0.028141,1.375159,-8.656001,-1.029539,1.198187,0.956790
26,50,3,6,1,51,Alabama,Elmore County,79303,79296,79465,...,3.235576,0.822717,1.760531,-1.507057,2.067820,3.674511,1.558176,2.306047,-0.951175,2.757093
27,50,3,6,1,53,Alabama,Escambia County,38319,38319,38309,...,-3.449988,-3.855889,-4.822706,-1.189831,1.190902,-3.397716,-3.803428,-4.769999,-1.136950,1.243830
28,50,3,6,1,55,Alabama,Etowah County,104430,104427,104442,...,-1.015919,2.062637,-1.931884,-1.726932,-2.082234,-0.632554,2.446383,-1.518596,-1.234901,-1.588308
29,50,3,6,1,57,Alabama,Fayette County,17241,17241,17231,...,-5.015601,-0.646640,-3.725937,0.296745,-2.797536,-5.132243,-0.705426,-3.785079,0.237396,-2.857058
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3163,50,2,3,55,131,Wisconsin,Washington County,131887,131885,131967,...,-0.794876,0.785279,-2.215465,1.601149,-0.434498,-0.431504,1.162817,-1.763330,2.104796,0.059931
3164,50,2,3,55,133,Wisconsin,Waukesha County,389891,389938,390076,...,-0.765799,2.128860,0.038132,0.760109,-0.719858,0.102448,3.180527,1.189727,2.077633,0.593567
3165,50,2,3,55,135,Wisconsin,Waupaca County,52410,52410,52422,...,3.111756,-2.241873,6.292687,-0.441031,-0.480617,3.359933,-2.011937,6.561277,-0.134227,-0.173022
3166,50,2,3,55,137,Wisconsin,Waushara County,24496,24496,24506,...,4.930022,-2.404973,-4.097017,-4.906711,-4.397793,5.174486,-2.160399,-3.810226,-4.535615,-4.024395
3167,50,2,3,55,139,Wisconsin,Winnebago County,166994,166994,167059,...,0.316712,2.889873,0.833819,-2.406192,-4.557985,0.842573,3.502335,1.531624,-1.545153,-3.685304
3168,50,2,3,55,141,Wisconsin,Wood County,74749,74749,74807,...,-4.081523,-5.019090,-6.901200,-5.596471,-3.958322,-3.733590,-4.562809,-6.442917,-5.040889,-3.414223
3169,40,4,8,56,0,Wyoming,Wyoming,563626,563767,564516,...,-0.381530,9.636214,4.487115,-4.788275,-3.221091,0.289680,10.694870,5.440390,-3.727831,-2.091573
3170,50,4,8,56,1,Wyoming,Albany County,36299,36299,36428,...,3.708956,2.637812,-3.544634,-3.334877,-9.911169,6.736119,6.433032,0.719587,1.429233,-5.166460
3171,50,4,8,56,3,Wyoming,Big Horn County,11668,11668,11672,...,4.868258,2.804930,16.815908,-8.026420,5.095861,4.868258,3.144921,17.236306,-7.608378,5.513554
3172,50,4,8,56,5,Wyoming,Campbell County,46133,46133,46244,...,-2.843479,15.601020,-5.895711,-8.550911,10.916963,-2.649606,15.558684,-5.916543,-8.509402,10.978525
3173,50,4,8,56,7,Wyoming,Carbon County,15885,15885,15837,...,-7.581980,-13.081441,3.178134,-2.970641,-23.300971,-7.392431,-12.636926,3.623073,-2.338590,-22.600668
3174,50,4,8,56,9,Wyoming,Converse County,13833,13833,13826,...,-12.847499,15.493820,19.035533,-20.550587,-0.070403,-12.774915,16.502720,20.093063,-19.358233,1.126443
3175,50,4,8,56,11,Wyoming,Crook County,7083,7083,7114,...,-1.544618,-4.202564,1.397819,6.378258,18.629317,-0.982939,-3.642222,2.096729,7.071547,19.309219
3176,50,4,8,56,13,Wyoming,Fremont County,40123,40123,40222,...,2.747083,7.782673,-4.990688,-12.331633,-13.673610,3.093562,8.027411,-4.747240,-12.013555,-13.352750
3177,50,4,8,56,15,Wyoming,Goshen County,13249,13247,13408,...,14.293649,3.961413,-8.079028,-7.017803,-11.899450,14.886132,4.841727,-6.903896,-5.761986,-10.635133
3178,50,4,8,56,17,Wyoming,Hot Springs County,4812,4812,4813,...,3.322604,6.208609,3.095336,-6.017222,-5.454164,5.191569,6.001656,2.888981,-6.224712,-5.663940
3179,50,4,8,56,19,Wyoming,Johnson County,8569,8569,8581,...,4.995063,-4.058912,-0.812583,-10.715742,0.933652,5.227392,-4.058912,-0.812583,-10.715742,0.933652
3180,50,4,8,56,21,Wyoming,Laramie County,91738,91881,92271,...,-1.200428,15.547274,4.787847,-1.226133,0.278940,-0.973320,17.914554,6.003143,-0.207819,1.673640
3181,50,4,8,56,23,Wyoming,Lincoln County,18106,18106,18091,...,-9.802564,-11.566801,13.564556,6.125989,1.555544,-9.691801,-11.566801,13.619696,6.234414,1.662823
3182,50,4,8,56,25,Wyoming,Natrona County,75450,75450,75472,...,7.189319,23.066162,24.322042,-0.958472,-0.061057,7.689674,23.749508,25.085233,-0.110593,0.793743
3183,50,4,8,56,27,Wyoming,Niobrara County,2484,2484,2492,...,-0.401849,0.806452,29.066295,-12.603387,7.492114,-0.401849,0.806452,29.066295,-12.603387,7.492114
3184,50,4,8,56,29,Wyoming,Park County,28205,28205,28259,...,4.582951,8.057765,7.641997,-9.252437,-2.878980,6.486639,11.127389,10.877797,-5.585731,0.856839
3185,50,4,8,56,31,Wyoming,Platte County,8667,8667,8678,...,4.373094,5.392073,2.634593,6.055759,4.662270,4.373094,4.933173,2.176403,5.598720,4.207414
3186,50,4,8,56,33,Wyoming,Sheridan County,29116,29116,29146,...,0.958559,8.425487,4.546373,3.678069,-3.298406,2.122524,9.342778,5.523001,4.781489,-2.198937
3187,50,4,8,56,35,Wyoming,Sublette County,10247,10247,10244,...,-23.741784,15.272374,-40.870074,-16.596273,-22.870900,-21.092907,16.828794,-39.211861,-14.409938,-20.664059
3188,50,4,8,56,37,Wyoming,Sweetwater County,43806,43806,43593,...,1.072643,16.243199,-5.339774,-14.252889,-14.248864,1.255221,16.243199,-5.295460,-14.075283,-14.070195
3189,50,4,8,56,39,Wyoming,Teton County,21294,21294,21297,...,-1.589565,0.972695,19.525929,14.143021,-0.564849,0.654527,2.408578,21.160658,16.308671,1.520747
3190,50,4,8,56,41,Wyoming,Uinta County,21118,21118,21102,...,-17.755986,-4.916350,-6.902954,-14.215862,-12.127022,-18.136812,-5.536861,-7.521840,-14.740608,-12.606351
3191,50,4,8,56,43,Wyoming,Washakie County,8533,8533,8545,...,-11.637475,-0.827815,-2.013502,-17.781491,1.682288,-11.990126,-1.182592,-2.250385,-18.020168,1.441961
3192,50,4,8,56,45,Wyoming,Weston County,7208,7208,7181,...,-11.752361,-8.040059,12.372583,1.533635,6.935294,-12.032179,-8.040059,12.372583,1.533635,6.935294

In [44]:
(df.where(df['SUMLEV']==50)
    .dropna()
    .set_index(['STNAME','CTYNAME'])
    .rename(columns={'ESTIMATESBASE2010': 'Estimates Base 2010'}))

                              SUMLEV  REGION  DIVISION  STATE  COUNTY  \
STNAME    CTYNAME
Alabama   Autauga County        50.0     3.0       6.0    1.0     1.0
          Baldwin County        50.0     3.0       6.0    1.0     3.0
          Barbour County        50.0     3.0       6.0    1.0     5.0
          Bibb County           50.0     3.0       6.0    1.0     7.0
          Blount County         50.0     3.0       6.0    1.0     9.0
          Bullock County        50.0     3.0       6.0    1.0    11.0
          Butler County         50.0     3.0       6.0    1.0    13.0
          Calhoun County        50.0     3.0       6.0    1.0    15.0
          Chambers County       50.0     3.0       6.0    1.0    17.0
          Cherokee County       50.0     3.0       6.0    1.0    19.0
          Chilton County        50.0     3.0       6.0    1.0    21.0
          Choctaw County        50.0     3.0       6.0    1.0    23.0
          Clarke County         50.0     3.0       6.0    1.0    25.0
          Clay County           50.0     3.0       6.0    1.0    27.0
          Cleburne County       50.0     3.0       6.0    1.0    29.0
          Coffee County         50.0     3.0       6.0    1.0    31.0
          Colbert County        50.0     3.0       6.0    1.0    33.0
          Conecuh County        50.0     3.0       6.0    1.0    35.0
          Coosa County          50.0     3.0       6.0    1.0    37.0
          Covington County      50.0     3.0       6.0    1.0    39.0
          Crenshaw County       50.0     3.0       6.0    1.0    41.0
          Cullman County        50.0     3.0       6.0    1.0    43.0
          Dale County           50.0     3.0       6.0    1.0    45.0
          Dallas County         50.0     3.0       6.0    1.0    47.0
          DeKalb County         50.0     3.0       6.0    1.0    49.0
          Elmore County         50.0     3.0       6.0    1.0    51.0
          Escambia County       50.0     3.0       6.0    1.0    53.0
          Etowah County         50.0     3.0       6.0    1.0    55.0
          Fayette County        50.0     3.0       6.0    1.0    57.0
          Franklin County       50.0     3.0       6.0    1.0    59.0
...                              ...     ...       ...    ...     ...
Wisconsin Washburn County       50.0     2.0       3.0   55.0   129.0
          Washington County     50.0     2.0       3.0   55.0   131.0
          Waukesha County       50.0     2.0       3.0   55.0   133.0
          Waupaca County        50.0     2.0       3.0   55.0   135.0
          Waushara County       50.0     2.0       3.0   55.0   137.0
          Winnebago County      50.0     2.0       3.0   55.0   139.0
          Wood County           50.0     2.0       3.0   55.0   141.0
Wyoming   Albany County         50.0     4.0       8.0   56.0     1.0
          Big Horn County       50.0     4.0       8.0   56.0     3.0
          Campbell County       50.0     4.0       8.0   56.0     5.0
          Carbon County         50.0     4.0       8.0   56.0     7.0
          Converse County       50.0     4.0       8.0   56.0     9.0
          Crook County          50.0     4.0       8.0   56.0    11.0
          Fremont County        50.0     4.0       8.0   56.0    13.0
          Goshen County         50.0     4.0       8.0   56.0    15.0
          Hot Springs County    50.0     4.0       8.0   56.0    17.0
          Johnson County        50.0     4.0       8.0   56.0    19.0
          Laramie County        50.0     4.0       8.0   56.0    21.0
          Lincoln County        50.0     4.0       8.0   56.0    23.0
          Natrona County        50.0     4.0       8.0   56.0    25.0
          Niobrara County       50.0     4.0       8.0   56.0    27.0
          Park County           50.0     4.0       8.0   56.0    29.0
          Platte County         50.0     4.0       8.0   56.0    31.0
          Sheridan County       50.0     4.0       8.0   56.0    33.0
          Sublette County       50.0     4.0       8.0   56.0    35.0
          Sweetwater County     50.0     4.0       8.0   56.0    37.0
          Teton County          50.0     4.0       8.0   56.0    39.0
          Uinta County          50.0     4.0       8.0   56.0    41.0
          Washakie County       50.0     4.0       8.0   56.0    43.0
          Weston County         50.0     4.0       8.0   56.0    45.0

                              CENSUS2010POP  Estimates Base 2010  \
STNAME    CTYNAME
Alabama   Autauga County            54571.0              54571.0
          Baldwin County           182265.0             182265.0
          Barbour County            27457.0              27457.0
          Bibb County               22915.0              22919.0
          Blount County             57322.0              57322.0
          Bullock County            10914.0              10915.0
          Butler County             20947.0              20946.0
          Calhoun County           118572.0             118586.0
          Chambers County           34215.0              34170.0
          Cherokee County           25989.0              25986.0
          Chilton County            43643.0              43631.0
          Choctaw County            13859.0              13858.0
          Clarke County             25833.0              25840.0
          Clay County               13932.0              13932.0
          Cleburne County           14972.0              14972.0
          Coffee County             49948.0              49948.0
          Colbert County            54428.0              54428.0
          Conecuh County            13228.0              13228.0
          Coosa County              11539.0              11758.0
          Covington County          37765.0              37765.0
          Crenshaw County           13906.0              13906.0
          Cullman County            80406.0              80410.0
          Dale County               50251.0              50251.0
          Dallas County             43820.0              43820.0
          DeKalb County             71109.0              71115.0
          Elmore County             79303.0              79296.0
          Escambia County           38319.0              38319.0
          Etowah County            104430.0             104427.0
          Fayette County            17241.0              17241.0
          Franklin County           31704.0              31709.0
...                                     ...                  ...
Wisconsin Washburn County           15911.0              15911.0
          Washington County        131887.0             131885.0
          Waukesha County          389891.0             389938.0
          Waupaca County            52410.0              52410.0
          Waushara County           24496.0              24496.0
          Winnebago County         166994.0             166994.0
          Wood County               74749.0              74749.0
Wyoming   Albany County             36299.0              36299.0
          Big Horn County           11668.0              11668.0
          Campbell County           46133.0              46133.0
          Carbon County             15885.0              15885.0
          Converse County           13833.0              13833.0
          Crook County               7083.0               7083.0
          Fremont County            40123.0              40123.0
          Goshen County             13249.0              13247.0
          Hot Springs County         4812.0               4812.0
          Johnson County             8569.0               8569.0
          Laramie County            91738.0              91881.0
          Lincoln County            18106.0              18106.0
          Natrona County            75450.0              75450.0
          Niobrara County            2484.0               2484.0
          Park County               28205.0              28205.0
          Platte County              8667.0               8667.0
          Sheridan County           29116.0              29116.0
          Sublette County           10247.0              10247.0
          Sweetwater County         43806.0              43806.0
          Teton County              21294.0              21294.0
          Uinta County              21118.0              21118.0
          Washakie County            8533.0               8533.0
          Weston County              7208.0               7208.0

                              POPESTIMATE2010  POPESTIMATE2011  \
STNAME    CTYNAME
Alabama   Autauga County              54660.0          55253.0
          Baldwin County             183193.0         186659.0
          Barbour County              27341.0          27226.0
          Bibb County                 22861.0          22733.0
          Blount County               57373.0          57711.0
          Bullock County              10887.0          10629.0
          Butler County               20944.0          20673.0
          Calhoun County             118437.0         117768.0
          Chambers County             34098.0          33993.0
          Cherokee County             25976.0          26080.0
          Chilton County              43665.0          43739.0
          Choctaw County              13841.0          13593.0
          Clarke County               25767.0          25570.0
          Clay County                 13880.0          13670.0
          Cleburne County             14973.0          14971.0
          Coffee County               50177.0          50448.0
          Colbert County              54514.0          54443.0
          Conecuh County              13208.0          13121.0
          Coosa County                11758.0          11348.0
          Covington County            37796.0          38060.0
          Crenshaw County             13853.0          13896.0
          Cullman County              80473.0          80469.0
          Dale County                 50358.0          50109.0
          Dallas County               43803.0          43178.0
          DeKalb County               71142.0          71387.0
          Elmore County               79465.0          80012.0
          Escambia County             38309.0          38213.0
          Etowah County              104442.0         104236.0
          Fayette County              17231.0          17062.0
          Franklin County             31734.0          31729.0
...                                       ...              ...
Wisconsin Washburn County             15930.0          15784.0
          Washington County          131967.0         132225.0
          Waukesha County            390076.0         390808.0
          Waupaca County              52422.0          52342.0
          Waushara County             24506.0          24581.0
          Winnebago County           167059.0         167630.0
          Wood County                 74807.0          74647.0
Wyoming   Albany County               36428.0          36908.0
          Big Horn County             11672.0          11745.0
          Campbell County             46244.0          46600.0
          Carbon County               15837.0          15817.0
          Converse County             13826.0          13728.0
          Crook County                 7114.0           7129.0
          Fremont County              40222.0          40591.0
          Goshen County               13408.0          13597.0
          Hot Springs County           4813.0           4818.0
          Johnson County               8581.0           8636.0
          Laramie County              92271.0          92663.0
          Lincoln County              18091.0          18022.0
          Natrona County              75472.0          76420.0
          Niobrara County              2492.0           2485.0
          Park County                 28259.0          28473.0
          Platte County                8678.0           8701.0
          Sheridan County             29146.0          29275.0
          Sublette County             10244.0          10142.0
          Sweetwater County           43593.0          44041.0
          Teton County                21297.0          21482.0
          Uinta County                21102.0          20912.0
          Washakie County              8545.0           8469.0
          Weston County                7181.0           7114.0

                              POPESTIMATE2012     ...       RDOMESTICMIG2011  \
STNAME    CTYNAME                                 ...
Alabama   Autauga County              55175.0     ...               7.242091
          Baldwin County             190396.0     ...              14.832960
          Barbour County              27159.0     ...              -4.728132
          Bibb County                 22642.0     ...              -5.527043
          Blount County               57776.0     ...               1.807375
          Bullock County              10606.0     ...             -30.953709
          Butler County               20408.0     ...             -14.032727
          Calhoun County             117286.0     ...              -6.155670
          Chambers County             34075.0     ...              -2.731639
          Cherokee County             26023.0     ...               6.339327
          Chilton County              43697.0     ...              -1.372935
          Choctaw County              13543.0     ...             -15.455274
          Clarke County               25144.0     ...              -6.194363
          Clay County                 13456.0     ...             -10.744102
          Cleburne County             14921.0     ...              -3.673524
          Coffee County               51173.0     ...               0.377640
          Colbert County              54472.0     ...              -0.073423
          Conecuh County              12996.0     ...              -4.861559
          Coosa County                11195.0     ...             -33.930581
          Covington County            37818.0     ...               6.696899
          Crenshaw County             13951.0     ...               1.729792
          Cullman County              80374.0     ...              -1.404233
          Dale County                 50324.0     ...             -10.749798
          Dallas County               42777.0     ...             -15.635599
          DeKalb County               70942.0     ...               0.294677
          Elmore County               80432.0     ...               3.235576
          Escambia County             38034.0     ...              -3.449988
          Etowah County              104235.0     ...              -1.015919
          Fayette County              16960.0     ...              -5.015601
          Franklin County             31648.0     ...              -1.638750
...                                       ...     ...                    ...
Wisconsin Washburn County             15831.0     ...              -6.873936
          Washington County          132649.0     ...              -0.794876
          Waukesha County            392710.0     ...              -0.765799
          Waupaca County              52035.0     ...               3.111756
          Waushara County             24484.0     ...               4.930022
          Winnebago County           168717.0     ...               0.316712
          Wood County                 74384.0     ...              -4.081523
Wyoming   Albany County               37396.0     ...               3.708956
          Big Horn County             11785.0     ...               4.868258
          Campbell County             47881.0     ...              -2.843479
          Carbon County               15678.0     ...              -7.581980
          Converse County             14025.0     ...             -12.847499
          Crook County                 7148.0     ...              -1.544618
          Fremont County              41129.0     ...               2.747083
          Goshen County               13666.0     ...              14.293649
          Hot Springs County           4846.0     ...               3.322604
          Johnson County               8610.0     ...               4.995063
          Laramie County              94894.0     ...              -1.200428
          Lincoln County              17943.0     ...              -9.802564
          Natrona County              78699.0     ...               7.189319
          Niobrara County              2475.0     ...              -0.401849
          Park County                 28863.0     ...               4.582951
          Platte County                8732.0     ...               4.373094
          Sheridan County             29594.0     ...               0.958559
          Sublette County             10418.0     ...             -23.741784
          Sweetwater County           45104.0     ...               1.072643
          Teton County                21697.0     ...              -1.589565
          Uinta County                20989.0     ...             -17.755986
          Washakie County              8443.0     ...             -11.637475
          Weston County                7065.0     ...             -11.752361

                              RDOMESTICMIG2012  RDOMESTICMIG2013  \
STNAME    CTYNAME
Alabama   Autauga County             -2.915927         -3.012349
          Baldwin County             17.647293         21.845705
          Barbour County             -2.500690         -7.056824
          Bibb County                -5.068871         -6.201001
          Blount County              -1.177622         -1.748766
          Bullock County             -5.180127         -1.130263
          Butler County             -11.684234         -5.655413
          Calhoun County             -4.611706         -5.524649
          Chambers County             3.849092          2.872721
          Cherokee County             1.113180          5.488706
          Chilton County             -2.653369          0.480044
          Choctaw County             -0.737028         -8.766391
          Clarke County             -17.667705         -0.318345
          Clay County               -13.345130          4.902871
          Cleburne County            -5.151880          7.345821
          Coffee County               7.675579        -13.146535
          Colbert County              1.065051          1.762390
          Conecuh County             -7.504690         -6.107224
          Coosa County              -10.291443         -4.313831
          Covington County           -4.612668          0.740271
          Crenshaw County             3.950156         -1.864936
          Cullman County             -1.019628          4.071247
          Dale County                -5.277150        -15.236079
          Dallas County             -11.308243        -16.745678
          DeKalb County              -9.302391         -1.748807
          Elmore County               0.822717          1.760531
          Escambia County            -3.855889         -4.822706
          Etowah County               2.062637         -1.931884
          Fayette County             -0.646640         -3.725937
          Franklin County            -5.459394         -8.043702
...                                        ...               ...
Wisconsin Washburn County             7.338289         -6.732724
          Washington County           0.785279         -2.215465
          Waukesha County             2.128860          0.038132
          Waupaca County             -2.241873          6.292687
          Waushara County            -2.404973         -4.097017
          Winnebago County            2.889873          0.833819
          Wood County                -5.019090         -6.901200
Wyoming   Albany County               2.637812         -3.544634
          Big Horn County             2.804930         16.815908
          Campbell County            15.601020         -5.895711
          Carbon County             -13.081441          3.178134

In [48]:
data = df[['POPESTIMATE2010',
                'POPESTIMATE2011',
                'POPESTIMATE2012',
                'POPESTIMATE2013',
                'POPESTIMATE2014',
                'POPESTIMATE2015']]

In [49]:
data

,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,POPESTIMATE2013,POPESTIMATE2014,POPESTIMATE2015
0,4785161,4801108,4816089,4830533,4846411,4858979
1,54660,55253,55175,55038,55290,55347
2,183193,186659,190396,195126,199713,203709
3,27341,27226,27159,26973,26815,26489
4,22861,22733,22642,22512,22549,22583
5,57373,57711,57776,57734,57658,57673
6,10887,10629,10606,10628,10829,10696
7,20944,20673,20408,20261,20276,20154
8,118437,117768,117286,116575,115993,115620
9,34098,33993,34075,34153,34052,34123
10,25976,26080,26023,26084,25995,25859
11,43665,43739,43697,43795,43921,43943
12,13841,13593,13543,13378,13289,13170
13,25767,25570,25144,25116,24847,24675
14,13880,13670,13456,13467,13538,13555
15,14973,14971,14921,15028,15072,15018
16,50177,50448,51173,50755,50831,51211
17,54514,54443,54472,54471,54480,54354
18,13208,13121,12996,12875,12662,12672
19,11758,11348,11195,11059,10807,10724
20,37796,38060,37818,37830,37888,37835
21,13853,13896,13951,13932,13948,13963
22,80473,80469,80374,80756,81221,82005
23,50358,50109,50324,49833,49501,49565
24,43803,43178,42777,42021,41662,41131
25,71142,71387,70942,70869,71012,71130
26,79465,80012,80432,80883,81022,81468
27,38309,38213,38034,37857,37784,37789
28,104442,104236,104235,103852,103452,103057
29,17231,17062,16960,16857,16842,16759
...,...,...,...,...,...,...
3163,131967,132225,132649,132758,133301,133674
3164,390076,390808,392710,394025,395335,396488
3165,52422,52342,52035,52213,52088,51945
3166,24506,24581,24484,24332,24173,24033
3167,167059,167630,168717,169486,169639,169546
3168,74807,74647,74384,73996,73597,73435
3169,564516,567768,577080,583131,584304,586107
3170,36428,36908,37396,37647,37918,37956
3171,11672,11745,11785,12002,11919,12022
3172,46244,46600,47881,48121,48243,49220
3173,15837,15817,15678,15787,15856,15559
3174,13826,13728,14025,14343,14172,14236
3175,7114,7129,7148,7160,7264,7444
3176,40222,40591,41129,41024,40717,40315
3177,13408,13597,13666,13565,13509,13383
3178,4813,4818,4846,4846,4793,4741
3179,8581,8636,8610,8619,8552,8585
3180,92271,92663,94894,96006,96469,97121
3181,18091,18022,17943,18328,18564,18722
3182,75472,76420,78699,81156,81603,82178
3183,2492,2485,2475,2548,2530,2542
3184,28259,28473,28863,29237,29126,29228
3185,8678,8701,8732,8728,8776,8812
3186,29146,29275,29594,29794,30020,30009
3187,10244,10142,10418,10086,10039,9899
3188,43593,44041,45104,45162,44925,44626
3189,21297,21482,21697,22347,22905,23125
3190,21102,20912,20989,21022,20903,20822
3191,8545,8469,8443,8443,8316,8328
3192,7181,7114,7065,7160,7185,7234

In [57]:
import numpy as np

def min_max(row):
    data = row[['POPESTIMATE2010',
                'POPESTIMATE2011',
                'POPESTIMATE2012',
                'POPESTIMATE2013',
                'POPESTIMATE2014',
                'POPESTIMATE2015']]
    return pd.Series({'min':np.min(data),'max':np.max(data)})

In [58]:
df.apply(min_max,axis=1)

          min      max
0     4785161  4858979
1       54660    55347
2      183193   203709
3       26489    27341
4       22512    22861
5       57373    57776
6       10606    10887
7       20154    20944
8      115620   118437
9       33993    34153
10      25859    26084
11      43665    43943
12      13170    13841
13      24675    25767
14      13456    13880
15      14921    15072
16      50177    51211
17      54354    54514
18      12662    13208
19      10724    11758
20      37796    38060
21      13853    13963
22      80374    82005
23      49501    50358
24      41131    43803
25      70869    71387
26      79465    81468
27      37784    38309
28     103057   104442
29      16759    17231
...       ...      ...
3163   131967   133674
3164   390076   396488
3165    51945    52422
3166    24033    24581
3167   167059   169639
3168    73435    74807
3169   564516   586107
3170    36428    37956
3171    11672    12022
3172    46244    49220
3173    15559    15856
3174    13728    14343
3175     7114     7444
3176    40222    41129
3177    13383    13666
3178     4741     4846
3179     8552     8636
3180    92271    97121
3181    17943    18722
3182    75472    82178
3183     2475     2548
3184    28259    29237
3185     8678     8812
3186    29146    30020
3187     9899    10418
3188    43593    45162
3189    21297    23125
3190    20822    21102
3191     8316     8545
3192     7065     7234

[3193 rows x 2 columns]

In [53]:
import numpy as np
def min_max(row):
    data = row[['POPESTIMATE2010',
                'POPESTIMATE2011',
                'POPESTIMATE2012',
                'POPESTIMATE2013',
                'POPESTIMATE2014',
                'POPESTIMATE2015']]
    row['max'] = np.max(data)
    row['min'] = np.min(data)
    return row
df.apply(min_max, axis=1)

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015,max,min
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594,4858979,4785161
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333,55347,54660
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499,203709,183193
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299,27341,26489
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861,22861,22512
5,50,3,6,1,9,Alabama,Blount County,57322,57322,57373,...,-1.748766,-2.062535,-1.369970,1.859511,-0.848580,-1.402476,-1.577232,-0.884411,57776,57373
6,50,3,6,1,11,Alabama,Bullock County,10914,10915,10887,...,-1.130263,14.354290,-16.167247,-29.001673,-2.825524,1.507017,17.243790,-13.193961,10887,10606
7,50,3,6,1,13,Alabama,Butler County,20947,20946,20944,...,-5.655413,1.085428,-6.529805,-13.936612,-11.586865,-5.557058,1.184103,-6.430868,20944,20154
8,50,3,6,1,15,Alabama,Calhoun County,118572,118586,118437,...,-5.524649,-4.463211,-3.376322,-5.791579,-4.092677,-5.062836,-3.912834,-2.806406,118437,115620
9,50,3,6,1,17,Alabama,Chambers County,34215,34170,34098,...,2.872721,-2.287222,1.349468,-1.821092,4.701181,3.781439,-1.290228,2.346901,34153,33993
10,50,3,6,1,19,Alabama,Cherokee County,25989,25986,25976,...,5.488706,-0.076806,-3.239866,6.416167,1.420264,5.757384,0.230419,-2.931307,26084,25859
11,50,3,6,1,21,Alabama,Chilton County,43643,43631,43665,...,0.480044,0.456017,-2.253483,-0.823761,-2.447504,0.868651,0.957636,-1.752709,43943,43665
12,50,3,6,1,23,Alabama,Choctaw County,13859,13858,13841,...,-8.766391,-1.274984,-5.291205,-15.528177,-0.737028,-8.766391,-1.274984,-5.291205,13841,13170
13,50,3,6,1,25,Alabama,Clarke County,25833,25840,25767,...,-0.318345,-8.686428,-5.613667,-6.077488,-17.509958,-0.159172,-8.486280,-5.411736,25767,24675
14,50,3,6,1,27,Alabama,Clay County,13932,13932,13880,...,4.902871,5.702648,3.912450,-10.816697,-13.345130,4.977157,5.776708,3.986270,13880,13456
15,50,3,6,1,29,Alabama,Cleburne County,14972,14972,14973,...,7.345821,3.654485,-3.123961,-3.673524,-5.151880,7.345821,3.654485,-3.123961,15072,14921
16,50,3,6,1,31,Alabama,Coffee County,49948,49948,50177,...,-13.146535,-3.602859,2.214774,2.166460,11.513368,-10.438741,-0.767822,5.350738,51211,50177
17,50,3,6,1,33,Alabama,Colbert County,54428,54428,54514,...,1.762390,1.835688,-0.110260,0.513964,1.469035,2.276420,2.533249,0.588052,54514,54354
18,50,3,6,1,35,Alabama,Conecuh County,13228,13228,13208,...,-6.107224,-14.645416,2.684140,-4.861559,-7.504690,-6.107224,-14.645416,2.684140,13208,12662
19,50,3,6,1,37,Alabama,Coosa County,11539,11758,11758,...,-4.313831,-22.958017,-5.387581,-34.017138,-10.380162,-4.403703,-23.049483,-5.387581,11758,10724
20,50,3,6,1,39,Alabama,Covington County,37765,37765,37796,...,0.740271,3.697932,-0.316945,6.881460,-4.559952,0.793147,3.750759,-0.264121,38060,37796
21,50,3,6,1,41,Alabama,Crenshaw County,13906,13906,13853,...,-1.864936,3.084648,3.439504,2.666763,5.099293,-0.502098,4.734577,5.087600,13963,13853
22,50,3,6,1,43,Alabama,Cullman County,80406,80410,80473,...,4.071247,5.087142,7.915406,-1.031427,-0.634159,4.542916,5.593387,8.417777,82005,80374
23,50,3,6,1,45,Alabama,Dale County,50251,50251,50358,...,-15.236079,-11.979785,-5.107706,-9.575283,-0.776637,-12.640155,-9.503292,-1.998668,50358,49501
24,50,3,6,1,47,Alabama,Dallas County,43820,43820,43803,...,-16.745678,-9.344789,-14.687232,-15.727573,-11.378047,-16.792849,-9.368689,-14.711389,43803,41131
25,50,3,6,1,49,Alabama,DeKalb County,71109,71115,71142,...,-1.748807,0.267830,0.028141,1.375159,-8.656001,-1.029539,1.198187,0.956790,71387,70869
26,50,3,6,1,51,Alabama,Elmore County,79303,79296,79465,...,1.760531,-1.507057,2.067820,3.674511,1.558176,2.306047,-0.951175,2.757093,81468,79465
27,50,3,6,1,53,Alabama,Escambia County,38319,38319,38309,...,-4.822706,-1.189831,1.190902,-3.397716,-3.803428,-4.769999,-1.136950,1.243830,38309,37784
28,50,3,6,1,55,Alabama,Etowah County,104430,104427,104442,...,-1.931884,-1.726932,-2.082234,-0.632554,2.446383,-1.518596,-1.234901,-1.588308,104442,103057
29,50,3,6,1,57,Alabama,Fayette County,17241,17241,17231,...,-3.725937,0.296745,-2.797536,-5.132243,-0.705426,-3.785079,0.237396,-2.857058,17231,16759
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3163,50,2,3,55,131,Wisconsin,Washington County,131887,131885,131967,...,-2.215465,1.601149,-0.434498,-0.431504,1.162817,-1.763330,2.104796,0.059931,133674,131967
3164,50,2,3,55,133,Wisconsin,Waukesha County,389891,389938,390076,...,0.038132,0.760109,-0.719858,0.102448,3.180527,1.189727,2.077633,0.593567,396488,390076
3165,50,2,3,55,135,Wisconsin,Waupaca County,52410,52410,52422,...,6.292687,-0.441031,-0.480617,3.359933,-2.011937,6.561277,-0.134227,-0.173022,52422,51945
3166,50,2,3,55,137,Wisconsin,Waushara County,24496,24496,24506,...,-4.097017,-4.906711,-4.397793,5.174486,-2.160399,-3.810226,-4.535615,-4.024395,24581,24033
3167,50,2,3,55,139,Wisconsin,Winnebago County,166994,166994,167059,...,0.833819,-2.406192,-4.557985,0.842573,3.502335,1.531624,-1.545153,-3.685304,169639,167059
3168,50,2,3,55,141,Wisconsin,Wood County,74749,74749,74807,...,-6.901200,-5.596471,-3.958322,-3.733590,-4.562809,-6.442917,-5.040889,-3.414223,74807,73435
3169,40,4,8,56,0,Wyoming,Wyoming,563626,563767,564516,...,4.487115,-4.788275,-3.221091,0.289680,10.694870,5.440390,-3.727831,-2.091573,586107,564516
3170,50,4,8,56,1,Wyoming,Albany County,36299,36299,36428,...,-3.544634,-3.334877,-9.911169,6.736119,6.433032,0.719587,1.429233,-5.166460,37956,36428
3171,50,4,8,56,3,Wyoming,Big Horn County,11668,11668,11672,...,16.815908,-8.026420,5.095861,4.868258,3.144921,17.236306,-7.608378,5.513554,12022,11672
3172,50,4,8,56,5,Wyoming,Campbell County,46133,46133,46244,...,-5.895711,-8.550911,10.916963,-2.649606,15.558684,-5.916543,-8.509402,10.978525,49220,46244
3173,50,4,8,56,7,Wyoming,Carbon County,15885,15885,15837,...,3.178134,-2.970641,-23.300971,-7.392431,-12.636926,3.623073,-2.338590,-22.600668,15856,15559
3174,50,4,8,56,9,Wyoming,Converse County,13833,13833,13826,...,19.035533,-20.550587,-0.070403,-12.774915,16.502720,20.093063,-19.358233,1.126443,14343,13728
3175,50,4,8,56,11,Wyoming,Crook County,7083,7083,7114,...,1.397819,6.378258,18.629317,-0.982939,-3.642222,2.096729,7.071547,19.309219,7444,7114
3176,50,4,8,56,13,Wyoming,Fremont County,40123,40123,40222,...,-4.990688,-12.331633,-13.673610,3.093562,8.027411,-4.747240,-12.013555,-13.352750,41129,40222
3177,50,4,8,56,15,Wyoming,Goshen County,13249,13247,13408,...,-8.079028,-7.017803,-11.899450,14.886132,4.841727,-6.903896,-5.761986,-10.635133,13666,13383
3178,50,4,8,56,17,Wyoming,Hot Springs County,4812,4812,4813,...,3.095336,-6.017222,-5.454164,5.191569,6.001656,2.888981,-6.224712,-5.663940,4846,4741
3179,50,4,8,56,19,Wyoming,Johnson County,8569,8569,8581,...,-0.812583,-10.715742,0.933652,5.227392,-4.058912,-0.812583,-10.715742,0.933652,8636,8552
3180,50,4,8,56,21,Wyoming,Laramie County,91738,91881,92271,...,4.787847,-1.226133,0.278940,-0.973320,17.914554,6.003143,-0.207819,1.673640,97121,92271
3181,50,4,8,56,23,Wyoming,Lincoln County,18106,18106,18091,...,13.564556,6.125989,1.555544,-9.691801,-11.566801,13.619696,6.234414,1.662823,18722,17943
3182,50,4,8,56,25,Wyoming,Natrona County,75450,75450,75472,...,24.322042,-0.958472,-0.061057,7.689674,23.749508,25.085233,-0.110593,0.793743,82178,75472
3183,50,4,8,56,27,Wyoming,Niobrara County,2484,2484,2492,...,29.066295,-12.603387,7.492114,-0.401849,0.806452,29.066295,-12.603387,7.492114,2548,2475
3184,50,4,8,56,29,Wyoming,Park County,28205,28205,28259,...,7.641997,-9.252437,-2.878980,6.486639,11.127389,10.877797,-5.585731,0.856839,29237,28259
3185,50,4,8,56,31,Wyoming,Platte County,8667,8667,8678,...,2.634593,6.055759,4.662270,4.373094,4.933173,2.176403,5.598720,4.207414,8812,8678
3186,50,4,8,56,33,Wyoming,Sheridan County,29116,29116,29146,...,4.546373,3.678069,-3.298406,2.122524,9.342778,5.523001,4.781489,-2.198937,30020,29146
3187,50,4,8,56,35,Wyoming,Sublette County,10247,10247,10244,...,-40.870074,-16.596273,-22.870900,-21.092907,16.828794,-39.211861,-14.409938,-20.664059,10418,9899
3188,50,4,8,56,37,Wyoming,Sweetwater County,43806,43806,43593,...,-5.339774,-14.252889,-14.248864,1.255221,16.243199,-5.295460,-14.075283,-14.070195,45162,43593
3189,50,4,8,56,39,Wyoming,Teton County,21294,21294,21297,...,19.525929,14.143021,-0.564849,0.654527,2.408578,21.160658,16.308671,1.520747,23125,21297
3190,50,4,8,56,41,Wyoming,Uinta County,21118,21118,21102,...,-6.902954,-14.215862,-12.127022,-18.136812,-5.536861,-7.521840,-14.740608,-12.606351,21102,20822
3191,50,4,8,56,43,Wyoming,Washakie County,8533,8533,8545,...,-2.013502,-17.781491,1.682288,-11.990126,-1.182592,-2.250385,-18.020168,1.441961,8545,8316
3192,50,4,8,56,45,Wyoming,Weston County,7208,7208,7181,...,12.372583,1.533635,6.935294,-12.032179,-8.040059,12.372583,1.533635,6.935294,7234,7065

In [54]:
rows = ['POPESTIMATE2010',
        'POPESTIMATE2011',
        'POPESTIMATE2012',
        'POPESTIMATE2013',
        'POPESTIMATE2014',
        'POPESTIMATE2015']
df.apply(lambda x: np.max(x[rows]), axis=1)

0       4858979
1         55347
2        203709
3         27341
4         22861
5         57776
6         10887
7         20944
8        118437
9         34153
10        26084
11        43943
12        13841
13        25767
14        13880
15        15072
16        51211
17        54514
18        13208
19        11758
20        38060
21        13963
22        82005
23        50358
24        43803
25        71387
26        81468
27        38309
28       104442
29        17231
         ...
3163     133674
3164     396488
3165      52422
3166      24581
3167     169639
3168      74807
3169     586107
3170      37956
3171      12022
3172      49220
3173      15856
3174      14343
3175       7444
3176      41129
3177      13666
3178       4846
3179       8636
3180      97121
3181      18722
3182      82178
3183       2548
3184      29237
3185       8812
3186      30020
3187      10418
3188      45162
3189      23125
3190      21102
3191       8545
3192       7234
Length: 3193, dtype: int64

In [5]:
import pandas as pd
import numpy as np
df = pd.read_csv('census.csv')
df = df[df['SUMLEV']==50]
df

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861
5,50,3,6,1,9,Alabama,Blount County,57322,57322,57373,...,1.807375,-1.177622,-1.748766,-2.062535,-1.369970,1.859511,-0.848580,-1.402476,-1.577232,-0.884411
6,50,3,6,1,11,Alabama,Bullock County,10914,10915,10887,...,-30.953709,-5.180127,-1.130263,14.354290,-16.167247,-29.001673,-2.825524,1.507017,17.243790,-13.193961
7,50,3,6,1,13,Alabama,Butler County,20947,20946,20944,...,-14.032727,-11.684234,-5.655413,1.085428,-6.529805,-13.936612,-11.586865,-5.557058,1.184103,-6.430868
8,50,3,6,1,15,Alabama,Calhoun County,118572,118586,118437,...,-6.155670,-4.611706,-5.524649,-4.463211,-3.376322,-5.791579,-4.092677,-5.062836,-3.912834,-2.806406
9,50,3,6,1,17,Alabama,Chambers County,34215,34170,34098,...,-2.731639,3.849092,2.872721,-2.287222,1.349468,-1.821092,4.701181,3.781439,-1.290228,2.346901
10,50,3,6,1,19,Alabama,Cherokee County,25989,25986,25976,...,6.339327,1.113180,5.488706,-0.076806,-3.239866,6.416167,1.420264,5.757384,0.230419,-2.931307
11,50,3,6,1,21,Alabama,Chilton County,43643,43631,43665,...,-1.372935,-2.653369,0.480044,0.456017,-2.253483,-0.823761,-2.447504,0.868651,0.957636,-1.752709
12,50,3,6,1,23,Alabama,Choctaw County,13859,13858,13841,...,-15.455274,-0.737028,-8.766391,-1.274984,-5.291205,-15.528177,-0.737028,-8.766391,-1.274984,-5.291205
13,50,3,6,1,25,Alabama,Clarke County,25833,25840,25767,...,-6.194363,-17.667705,-0.318345,-8.686428,-5.613667,-6.077488,-17.509958,-0.159172,-8.486280,-5.411736
14,50,3,6,1,27,Alabama,Clay County,13932,13932,13880,...,-10.744102,-13.345130,4.902871,5.702648,3.912450,-10.816697,-13.345130,4.977157,5.776708,3.986270
15,50,3,6,1,29,Alabama,Cleburne County,14972,14972,14973,...,-3.673524,-5.151880,7.345821,3.654485,-3.123961,-3.673524,-5.151880,7.345821,3.654485,-3.123961
16,50,3,6,1,31,Alabama,Coffee County,49948,49948,50177,...,0.377640,7.675579,-13.146535,-3.602859,2.214774,2.166460,11.513368,-10.438741,-0.767822,5.350738
17,50,3,6,1,33,Alabama,Colbert County,54428,54428,54514,...,-0.073423,1.065051,1.762390,1.835688,-0.110260,0.513964,1.469035,2.276420,2.533249,0.588052
18,50,3,6,1,35,Alabama,Conecuh County,13228,13228,13208,...,-4.861559,-7.504690,-6.107224,-14.645416,2.684140,-4.861559,-7.504690,-6.107224,-14.645416,2.684140
19,50,3,6,1,37,Alabama,Coosa County,11539,11758,11758,...,-33.930581,-10.291443,-4.313831,-22.958017,-5.387581,-34.017138,-10.380162,-4.403703,-23.049483,-5.387581
20,50,3,6,1,39,Alabama,Covington County,37765,37765,37796,...,6.696899,-4.612668,0.740271,3.697932,-0.316945,6.881460,-4.559952,0.793147,3.750759,-0.264121
21,50,3,6,1,41,Alabama,Crenshaw County,13906,13906,13853,...,1.729792,3.950156,-1.864936,3.084648,3.439504,2.666763,5.099293,-0.502098,4.734577,5.087600
22,50,3,6,1,43,Alabama,Cullman County,80406,80410,80473,...,-1.404233,-1.019628,4.071247,5.087142,7.915406,-1.031427,-0.634159,4.542916,5.593387,8.417777
23,50,3,6,1,45,Alabama,Dale County,50251,50251,50358,...,-10.749798,-5.277150,-15.236079,-11.979785,-5.107706,-9.575283,-0.776637,-12.640155,-9.503292,-1.998668
24,50,3,6,1,47,Alabama,Dallas County,43820,43820,43803,...,-15.635599,-11.308243,-16.745678,-9.344789,-14.687232,-15.727573,-11.378047,-16.792849,-9.368689,-14.711389
25,50,3,6,1,49,Alabama,DeKalb County,71109,71115,71142,...,0.294677,-9.302391,-1.748807,0.267830,0.028141,1.375159,-8.656001,-1.029539,1.198187,0.956790
26,50,3,6,1,51,Alabama,Elmore County,79303,79296,79465,...,3.235576,0.822717,1.760531,-1.507057,2.067820,3.674511,1.558176,2.306047,-0.951175,2.757093
27,50,3,6,1,53,Alabama,Escambia County,38319,38319,38309,...,-3.449988,-3.855889,-4.822706,-1.189831,1.190902,-3.397716,-3.803428,-4.769999,-1.136950,1.243830
28,50,3,6,1,55,Alabama,Etowah County,104430,104427,104442,...,-1.015919,2.062637,-1.931884,-1.726932,-2.082234,-0.632554,2.446383,-1.518596,-1.234901,-1.588308
29,50,3,6,1,57,Alabama,Fayette County,17241,17241,17231,...,-5.015601,-0.646640,-3.725937,0.296745,-2.797536,-5.132243,-0.705426,-3.785079,0.237396,-2.857058
30,50,3,6,1,59,Alabama,Franklin County,31704,31709,31734,...,-1.638750,-5.459394,-8.043702,-1.267849,-2.401719,0.063029,-3.471291,-5.700261,1.553115,0.442422
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3162,50,2,3,55,129,Wisconsin,Washburn County,15911,15911,15930,...,-6.873936,7.338289,-6.732724,3.510452,-5.123279,-6.747809,7.464811,-6.605691,3.638104,-4.995197
3163,50,2,3,55,131,Wisconsin,Washington County,131887,131885,131967,...,-0.794876,0.785279,-2.215465,1.601149,-0.434498,-0.431504,1.162817,-1.763330,2.104796,0.059931
3164,50,2,3,55,133,Wisconsin,Waukesha County,389891,389938,390076,...,-0.765799,2.128860,0.038132,0.760109,-0.719858,0.102448,3.180527,1.189727,2.077633,0.593567
3165,50,2,3,55,135,Wisconsin,Waupaca County,52410,52410,52422,...,3.111756,-2.241873,6.292687,-0.441031,-0.480617,3.359933,-2.011937,6.561277,-0.134227,-0.173022
3166,50,2,3,55,137,Wisconsin,Waushara County,24496,24496,24506,...,4.930022,-2.404973,-4.097017,-4.906711,-4.397793,5.174486,-2.160399,-3.810226,-4.535615,-4.024395
3167,50,2,3,55,139,Wisconsin,Winnebago County,166994,166994,167059,...,0.316712,2.889873,0.833819,-2.406192,-4.557985,0.842573,3.502335,1.531624,-1.545153,-3.685304
3168,50,2,3,55,141,Wisconsin,Wood County,74749,74749,74807,...,-4.081523,-5.019090,-6.901200,-5.596471,-3.958322,-3.733590,-4.562809,-6.442917,-5.040889,-3.414223
3170,50,4,8,56,1,Wyoming,Albany County,36299,36299,36428,...,3.708956,2.637812,-3.544634,-3.334877,-9.911169,6.736119,6.433032,0.719587,1.429233,-5.166460
3171,50,4,8,56,3,Wyoming,Big Horn County,11668,11668,11672,...,4.868258,2.804930,16.815908,-8.026420,5.095861,4.868258,3.144921,17.236306,-7.608378,5.513554
3172,50,4,8,56,5,Wyoming,Campbell County,46133,46133,46244,...,-2.843479,15.601020,-5.895711,-8.550911,10.916963,-2.649606,15.558684,-5.916543,-8.509402,10.978525
3173,50,4,8,56,7,Wyoming,Carbon County,15885,15885,15837,...,-7.581980,-13.081441,3.178134,-2.970641,-23.300971,-7.392431,-12.636926,3.623073,-2.338590,-22.600668
3174,50,4,8,56,9,Wyoming,Converse County,13833,13833,13826,...,-12.847499,15.493820,19.035533,-20.550587,-0.070403,-12.774915,16.502720,20.093063,-19.358233,1.126443
3175,50,4,8,56,11,Wyoming,Crook County,7083,7083,7114,...,-1.544618,-4.202564,1.397819,6.378258,18.629317,-0.982939,-3.642222,2.096729,7.071547,19.309219
3176,50,4,8,56,13,Wyoming,Fremont County,40123,40123,40222,...,2.747083,7.782673,-4.990688,-12.331633,-13.673610,3.093562,8.027411,-4.747240,-12.013555,-13.352750
3177,50,4,8,56,15,Wyoming,Goshen County,13249,13247,13408,...,14.293649,3.961413,-8.079028,-7.017803,-11.899450,14.886132,4.841727,-6.903896,-5.761986,-10.635133
3178,50,4,8,56,17,Wyoming,Hot Springs County,4812,4812,4813,...,3.322604,6.208609,3.095336,-6.017222,-5.454164,5.191569,6.001656,2.888981,-6.224712,-5.663940
3179,50,4,8,56,19,Wyoming,Johnson County,8569,8569,8581,...,4.995063,-4.058912,-0.812583,-10.715742,0.933652,5.227392,-4.058912,-0.812583,-10.715742,0.933652
3180,50,4,8,56,21,Wyoming,Laramie County,91738,91881,92271,...,-1.200428,15.547274,4.787847,-1.226133,0.278940,-0.973320,17.914554,6.003143,-0.207819,1.673640
3181,50,4,8,56,23,Wyoming,Lincoln County,18106,18106,18091,...,-9.802564,-11.566801,13.564556,6.125989,1.555544,-9.691801,-11.566801,13.619696,6.234414,1.662823
3182,50,4,8,56,25,Wyoming,Natrona County,75450,75450,75472,...,7.189319,23.066162,24.322042,-0.958472,-0.061057,7.689674,23.749508,25.085233,-0.110593,0.793743
3183,50,4,8,56,27,Wyoming,Niobrara County,2484,2484,2492,...,-0.401849,0.806452,29.066295,-12.603387,7.492114,-0.401849,0.806452,29.066295,-12.603387,7.492114
3184,50,4,8,56,29,Wyoming,Park County,28205,28205,28259,...,4.582951,8.057765,7.641997,-9.252437,-2.878980,6.486639,11.127389,10.877797,-5.585731,0.856839
3185,50,4,8,56,31,Wyoming,Platte County,8667,8667,8678,...,4.373094,5.392073,2.634593,6.055759,4.662270,4.373094,4.933173,2.176403,5.598720,4.207414
3186,50,4,8,56,33,Wyoming,Sheridan County,29116,29116,29146,...,0.958559,8.425487,4.546373,3.678069,-3.298406,2.122524,9.342778,5.523001,4.781489,-2.198937
3187,50,4,8,56,35,Wyoming,Sublette County,10247,10247,10244,...,-23.741784,15.272374,-40.870074,-16.596273,-22.870900,-21.092907,16.828794,-39.211861,-14.409938,-20.664059
3188,50,4,8,56,37,Wyoming,Sweetwater County,43806,43806,43593,...,1.072643,16.243199,-5.339774,-14.252889,-14.248864,1.255221,16.243199,-5.295460,-14.075283,-14.070195
3189,50,4,8,56,39,Wyoming,Teton County,21294,21294,21297,...,-1.589565,0.972695,19.525929,14.143021,-0.564849,0.654527,2.408578,21.160658,16.308671,1.520747
3190,50,4,8,56,41,Wyoming,Uinta County,21118,21118,21102,...,-17.755986,-4.916350,-6.902954,-14.215862,-12.127022,-18.136812,-5.536861,-7.521840,-14.740608,-12.606351
3191,50,4,8,56,43,Wyoming,Washakie County,8533,8533,8545,...,-11.637475,-0.827815,-2.013502,-17.781491,1.682288,-11.990126,-1.182592,-2.250385,-18.020168,1.441961
3192,50,4,8,56,45,Wyoming,Weston County,7208,7208,7181,...,-11.752361,-8.040059,12.372583,1.533635,6.935294,-12.032179,-8.040059,12.372583,1.533635,6.935294

In [60]:
df['STNAME'].unique()

array(['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California',
       'Colorado', 'Connecticut', 'Delaware', 'District of Columbia',
       'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana',
       'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland',
       'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi',
       'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire',
       'New Jersey', 'New Mexico', 'New York', 'North Carolina',
       'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania',
       'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee',
       'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington',
       'West Virginia', 'Wisconsin', 'Wyoming'], dtype=object)

In [ ]:
df.where(df['COUNTY']>5).dropna()['CENSUS2010POP']##for checking

In [9]:
%%timeit -n 1
for state in df['STNAME'].unique():
    avg=np.average(df.where(df['STNAME']==state).dropna()['CENSUS2010POP'])
    print('Countries in state'+ state+'have an average population of'+str(avg))

Countries in stateAlabamahave an average population of71339.34328358209
Countries in stateAlaskahave an average population of24490.724137931036
Countries in stateArizonahave an average population of426134.4666666667
Countries in stateArkansashave an average population of38878.90666666667
Countries in stateCaliforniahave an average population of642309.5862068966
Countries in stateColoradohave an average population of78581.1875
Countries in stateConnecticuthave an average population of446762.125
Countries in stateDelawarehave an average population of299311.3333333333
Countries in stateDistrict of Columbiahave an average population of601723.0
Countries in stateFloridahave an average population of280616.5671641791
Countries in stateGeorgiahave an average population of60928.63522012578
Countries in stateHawaiihave an average population of272060.2
Countries in stateIdahohave an average population of35626.86363636364
Countries in stateIllinoishave an average population of125790.50980392157
Countries in stateIndianahave an average population of70476.10869565218
Countries in stateIowahave an average population of30771.262626262625
Countries in stateKansashave an average population of27172.55238095238
Countries in stateKentuckyhave an average population of36161.39166666667
Countries in stateLouisianahave an average population of70833.9375
Countries in stateMainehave an average population of83022.5625
Countries in stateMarylandhave an average population of240564.66666666666
Countries in stateMassachusettshave an average population of467687.78571428574
Countries in stateMichiganhave an average population of119080.0
Countries in stateMinnesotahave an average population of60964.65517241379
Countries in stateMississippihave an average population of36186.54878048781
Countries in stateMissourihave an average population of52077.62608695652
Countries in stateMontanahave an average population of17668.125
Countries in stateNebraskahave an average population of19638.075268817203
Countries in stateNevadahave an average population of158855.9411764706
Countries in stateNew Hampshirehave an average population of131647.0
Countries in stateNew Jerseyhave an average population of418661.61904761905
Countries in stateNew Mexicohave an average population of62399.36363636364
Countries in stateNew Yorkhave an average population of312550.03225806454
Countries in stateNorth Carolinahave an average population of95354.83
Countries in stateNorth Dakotahave an average population of12690.396226415094
Countries in stateOhiohave an average population of131096.63636363635
Countries in stateOklahomahave an average population of48718.844155844155
Countries in stateOregonhave an average population of106418.72222222222
Countries in statePennsylvaniahave an average population of189587.74626865672
Countries in stateRhode Islandhave an average population of210513.4
Countries in stateSouth Carolinahave an average population of100551.39130434782
Countries in stateSouth Dakotahave an average population of12336.060606060606
Countries in stateTennesseehave an average population of66801.1052631579
Countries in stateTexashave an average population of98998.27165354331
Countries in stateUtahhave an average population of95306.37931034483
Countries in stateVermonthave an average population of44695.78571428572
Countries in stateVirginiahave an average population of60111.29323308271
Countries in stateWashingtonhave an average population of172424.10256410256
Countries in stateWest Virginiahave an average population of33690.8
Countries in stateWisconsinhave an average population of78985.91666666667
Countries in stateWyominghave an average population of24505.478260869564
Countries in stateAlabamahave an average population of71339.34328358209
Countries in stateAlaskahave an average population of24490.724137931036
Countries in stateArizonahave an average population of426134.4666666667
Countries in stateArkansashave an average population of38878.90666666667
Countries in stateCaliforniahave an average population of642309.5862068966
Countries in stateColoradohave an average population of78581.1875
Countries in stateConnecticuthave an average population of446762.125
Countries in stateDelawarehave an average population of299311.3333333333
Countries in stateDistrict of Columbiahave an average population of601723.0
Countries in stateFloridahave an average population of280616.5671641791
Countries in stateGeorgiahave an average population of60928.63522012578
Countries in stateHawaiihave an average population of272060.2
Countries in stateIdahohave an average population of35626.86363636364
Countries in stateIllinoishave an average population of125790.50980392157
Countries in stateIndianahave an average population of70476.10869565218
Countries in stateIowahave an average population of30771.262626262625
Countries in stateKansashave an average population of27172.55238095238
Countries in stateKentuckyhave an average population of36161.39166666667
Countries in stateLouisianahave an average population of70833.9375
Countries in stateMainehave an average population of83022.5625
Countries in stateMarylandhave an average population of240564.66666666666
Countries in stateMassachusettshave an average population of467687.78571428574
Countries in stateMichiganhave an average population of119080.0
Countries in stateMinnesotahave an average population of60964.65517241379
Countries in stateMississippihave an average population of36186.54878048781
Countries in stateMissourihave an average population of52077.62608695652
Countries in stateMontanahave an average population of17668.125
Countries in stateNebraskahave an average population of19638.075268817203
Countries in stateNevadahave an average population of158855.9411764706
Countries in stateNew Hampshirehave an average population of131647.0
Countries in stateNew Jerseyhave an average population of418661.61904761905
Countries in stateNew Mexicohave an average population of62399.36363636364
Countries in stateNew Yorkhave an average population of312550.03225806454
Countries in stateNorth Carolinahave an average population of95354.83
Countries in stateNorth Dakotahave an average population of12690.396226415094
Countries in stateOhiohave an average population of131096.63636363635
Countries in stateOklahomahave an average population of48718.844155844155
Countries in stateOregonhave an average population of106418.72222222222
Countries in statePennsylvaniahave an average population of189587.74626865672
Countries in stateRhode Islandhave an average population of210513.4
Countries in stateSouth Carolinahave an average population of100551.39130434782
Countries in stateSouth Dakotahave an average population of12336.060606060606
Countries in stateTennesseehave an average population of66801.1052631579
Countries in stateTexashave an average population of98998.27165354331
Countries in stateUtahhave an average population of95306.37931034483
Countries in stateVermonthave an average population of44695.78571428572
Countries in stateVirginiahave an average population of60111.29323308271
Countries in stateWashingtonhave an average population of172424.10256410256
Countries in stateWest Virginiahave an average population of33690.8
Countries in stateWisconsinhave an average population of78985.91666666667
Countries in stateWyominghave an average population of24505.478260869564
Countries in stateAlabamahave an average population of71339.34328358209
Countries in stateAlaskahave an average population of24490.724137931036
Countries in stateArizonahave an average population of426134.4666666667
Countries in stateArkansashave an average population of38878.90666666667
Countries in stateCaliforniahave an average population of642309.5862068966
Countries in stateColoradohave an average population of78581.1875
Countries in stateConnecticuthave an average population of446762.125
Countries in stateDelawarehave an average population of299311.3333333333
Countries in stateDistrict of Columbiahave an average population of601723.0
Countries in stateFloridahave an average population of280616.5671641791
Countries in stateGeorgiahave an average population of60928.63522012578
Countries in stateHawaiihave an average population of272060.2
Countries in stateIdahohave an average population of35626.86363636364

Countries in stateIllinoishave an average population of125790.50980392157
Countries in stateIndianahave an average population of70476.10869565218
Countries in stateIowahave an average population of30771.262626262625
Countries in stateKansashave an average population of27172.55238095238
Countries in stateKentuckyhave an average population of36161.39166666667
Countries in stateLouisianahave an average population of70833.9375
Countries in stateMainehave an average population of83022.5625
Countries in stateMarylandhave an average population of240564.66666666666
Countries in stateMassachusettshave an average population of467687.78571428574
Countries in stateMichiganhave an average population of119080.0
Countries in stateMinnesotahave an average population of60964.65517241379
Countries in stateMississippihave an average population of36186.54878048781
Countries in stateMissourihave an average population of52077.62608695652
Countries in stateMontanahave an average population of17668.125
Countries in stateNebraskahave an average population of19638.075268817203
Countries in stateNevadahave an average population of158855.9411764706
Countries in stateNew Hampshirehave an average population of131647.0
Countries in stateNew Jerseyhave an average population of418661.61904761905
Countries in stateNew Mexicohave an average population of62399.36363636364
Countries in stateNew Yorkhave an average population of312550.03225806454
Countries in stateNorth Carolinahave an average population of95354.83
Countries in stateNorth Dakotahave an average population of12690.396226415094
Countries in stateOhiohave an average population of131096.63636363635
Countries in stateOklahomahave an average population of48718.844155844155
Countries in stateOregonhave an average population of106418.72222222222
Countries in statePennsylvaniahave an average population of189587.74626865672
Countries in stateRhode Islandhave an average population of210513.4
Countries in stateSouth Carolinahave an average population of100551.39130434782
Countries in stateSouth Dakotahave an average population of12336.060606060606
Countries in stateTennesseehave an average population of66801.1052631579
Countries in stateTexashave an average population of98998.27165354331
Countries in stateUtahhave an average population of95306.37931034483
Countries in stateVermonthave an average population of44695.78571428572
Countries in stateVirginiahave an average population of60111.29323308271
Countries in stateWashingtonhave an average population of172424.10256410256
Countries in stateWest Virginiahave an average population of33690.8
Countries in stateWisconsinhave an average population of78985.91666666667
Countries in stateWyominghave an average population of24505.478260869564
Countries in stateAlabamahave an average population of71339.34328358209
Countries in stateAlaskahave an average population of24490.724137931036
Countries in stateArizonahave an average population of426134.4666666667
Countries in stateArkansashave an average population of38878.90666666667
Countries in stateCaliforniahave an average population of642309.5862068966
Countries in stateColoradohave an average population of78581.1875
Countries in stateConnecticuthave an average population of446762.125
Countries in stateDelawarehave an average population of299311.3333333333
Countries in stateDistrict of Columbiahave an average population of601723.0
Countries in stateFloridahave an average population of280616.5671641791
Countries in stateGeorgiahave an average population of60928.63522012578
Countries in stateHawaiihave an average population of272060.2
Countries in stateIdahohave an average population of35626.86363636364
Countries in stateIllinoishave an average population of125790.50980392157
Countries in stateIndianahave an average population of70476.10869565218
Countries in stateIowahave an average population of30771.262626262625
Countries in stateKansashave an average population of27172.55238095238
Countries in stateKentuckyhave an average population of36161.39166666667
Countries in stateLouisianahave an average population of70833.9375
Countries in stateMainehave an average population of83022.5625
Countries in stateMarylandhave an average population of240564.66666666666
Countries in stateMassachusettshave an average population of467687.78571428574
Countries in stateMichiganhave an average population of119080.0
Countries in stateMinnesotahave an average population of60964.65517241379
Countries in stateMississippihave an average population of36186.54878048781
Countries in stateMissourihave an average population of52077.62608695652
Countries in stateMontanahave an average population of17668.125
Countries in stateNebraskahave an average population of19638.075268817203
Countries in stateNevadahave an average population of158855.9411764706
Countries in stateNew Hampshirehave an average population of131647.0
Countries in stateNew Jerseyhave an average population of418661.61904761905
Countries in stateNew Mexicohave an average population of62399.36363636364
Countries in stateNew Yorkhave an average population of312550.03225806454
Countries in stateNorth Carolinahave an average population of95354.83
Countries in stateNorth Dakotahave an average population of12690.396226415094
Countries in stateOhiohave an average population of131096.63636363635
Countries in stateOklahomahave an average population of48718.844155844155
Countries in stateOregonhave an average population of106418.72222222222
Countries in statePennsylvaniahave an average population of189587.74626865672
Countries in stateRhode Islandhave an average population of210513.4
Countries in stateSouth Carolinahave an average population of100551.39130434782
Countries in stateSouth Dakotahave an average population of12336.060606060606
Countries in stateTennesseehave an average population of66801.1052631579
Countries in stateTexashave an average population of98998.27165354331
Countries in stateUtahhave an average population of95306.37931034483
Countries in stateVermonthave an average population of44695.78571428572
Countries in stateVirginiahave an average population of60111.29323308271
Countries in stateWashingtonhave an average population of172424.10256410256
Countries in stateWest Virginiahave an average population of33690.8
Countries in stateWisconsinhave an average population of78985.91666666667
Countries in stateWyominghave an average population of24505.478260869564
Countries in stateAlabamahave an average population of71339.34328358209
Countries in stateAlaskahave an average population of24490.724137931036
Countries in stateArizonahave an average population of426134.4666666667
Countries in stateArkansashave an average population of38878.90666666667
Countries in stateCaliforniahave an average population of642309.5862068966
Countries in stateColoradohave an average population of78581.1875
Countries in stateConnecticuthave an average population of446762.125
Countries in stateDelawarehave an average population of299311.3333333333
Countries in stateDistrict of Columbiahave an average population of601723.0
Countries in stateFloridahave an average population of280616.5671641791
Countries in stateGeorgiahave an average population of60928.63522012578
Countries in stateHawaiihave an average population of272060.2
Countries in stateIdahohave an average population of35626.86363636364
Countries in stateIllinoishave an average population of125790.50980392157
Countries in stateIndianahave an average population of70476.10869565218
Countries in stateIowahave an average population of30771.262626262625
Countries in stateKansashave an average population of27172.55238095238
Countries in stateKentuckyhave an average population of36161.39166666667
Countries in stateLouisianahave an average population of70833.9375
Countries in stateMainehave an average population of83022.5625
Countries in stateMarylandhave an average population of240564.66666666666
Countries in stateMassachusettshave an average population of467687.78571428574
Countries in stateMichiganhave an average population of119080.0
Countries in stateMinnesotahave an average population of60964.65517241379
Countries in stateMississippihave an average population of36186.54878048781
Countries in stateMissourihave an average population of52077.62608695652
Countries in stateMontanahave an average population of17668.125
Countries in stateNebraskahave an average population of19638.075268817203
Countries in stateNevadahave an average population of158855.9411764706

Countries in stateNew Hampshirehave an average population of131647.0
Countries in stateNew Jerseyhave an average population of418661.61904761905
Countries in stateNew Mexicohave an average population of62399.36363636364
Countries in stateNew Yorkhave an average population of312550.03225806454
Countries in stateNorth Carolinahave an average population of95354.83
Countries in stateNorth Dakotahave an average population of12690.396226415094
Countries in stateOhiohave an average population of131096.63636363635
Countries in stateOklahomahave an average population of48718.844155844155
Countries in stateOregonhave an average population of106418.72222222222
Countries in statePennsylvaniahave an average population of189587.74626865672
Countries in stateRhode Islandhave an average population of210513.4
Countries in stateSouth Carolinahave an average population of100551.39130434782
Countries in stateSouth Dakotahave an average population of12336.060606060606
Countries in stateTennesseehave an average population of66801.1052631579
Countries in stateTexashave an average population of98998.27165354331
Countries in stateUtahhave an average population of95306.37931034483
Countries in stateVermonthave an average population of44695.78571428572
Countries in stateVirginiahave an average population of60111.29323308271
Countries in stateWashingtonhave an average population of172424.10256410256
Countries in stateWest Virginiahave an average population of33690.8
Countries in stateWisconsinhave an average population of78985.91666666667
Countries in stateWyominghave an average population of24505.478260869564
Countries in stateAlabamahave an average population of71339.34328358209
Countries in stateAlaskahave an average population of24490.724137931036
Countries in stateArizonahave an average population of426134.4666666667
Countries in stateArkansashave an average population of38878.90666666667
Countries in stateCaliforniahave an average population of642309.5862068966
Countries in stateColoradohave an average population of78581.1875
Countries in stateConnecticuthave an average population of446762.125
Countries in stateDelawarehave an average population of299311.3333333333
Countries in stateDistrict of Columbiahave an average population of601723.0
Countries in stateFloridahave an average population of280616.5671641791
Countries in stateGeorgiahave an average population of60928.63522012578
Countries in stateHawaiihave an average population of272060.2
Countries in stateIdahohave an average population of35626.86363636364
Countries in stateIllinoishave an average population of125790.50980392157
Countries in stateIndianahave an average population of70476.10869565218
Countries in stateIowahave an average population of30771.262626262625
Countries in stateKansashave an average population of27172.55238095238
Countries in stateKentuckyhave an average population of36161.39166666667
Countries in stateLouisianahave an average population of70833.9375
Countries in stateMainehave an average population of83022.5625
Countries in stateMarylandhave an average population of240564.66666666666
Countries in stateMassachusettshave an average population of467687.78571428574
Countries in stateMichiganhave an average population of119080.0
Countries in stateMinnesotahave an average population of60964.65517241379
Countries in stateMississippihave an average population of36186.54878048781
Countries in stateMissourihave an average population of52077.62608695652
Countries in stateMontanahave an average population of17668.125
Countries in stateNebraskahave an average population of19638.075268817203
Countries in stateNevadahave an average population of158855.9411764706
Countries in stateNew Hampshirehave an average population of131647.0
Countries in stateNew Jerseyhave an average population of418661.61904761905
Countries in stateNew Mexicohave an average population of62399.36363636364
Countries in stateNew Yorkhave an average population of312550.03225806454
Countries in stateNorth Carolinahave an average population of95354.83
Countries in stateNorth Dakotahave an average population of12690.396226415094
Countries in stateOhiohave an average population of131096.63636363635
Countries in stateOklahomahave an average population of48718.844155844155
Countries in stateOregonhave an average population of106418.72222222222
Countries in statePennsylvaniahave an average population of189587.74626865672
Countries in stateRhode Islandhave an average population of210513.4
Countries in stateSouth Carolinahave an average population of100551.39130434782
Countries in stateSouth Dakotahave an average population of12336.060606060606
Countries in stateTennesseehave an average population of66801.1052631579
Countries in stateTexashave an average population of98998.27165354331
Countries in stateUtahhave an average population of95306.37931034483
Countries in stateVermonthave an average population of44695.78571428572
Countries in stateVirginiahave an average population of60111.29323308271
Countries in stateWashingtonhave an average population of172424.10256410256
Countries in stateWest Virginiahave an average population of33690.8
Countries in stateWisconsinhave an average population of78985.91666666667
Countries in stateWyominghave an average population of24505.478260869564
Countries in stateAlabamahave an average population of71339.34328358209
Countries in stateAlaskahave an average population of24490.724137931036
Countries in stateArizonahave an average population of426134.4666666667
Countries in stateArkansashave an average population of38878.90666666667
Countries in stateCaliforniahave an average population of642309.5862068966
Countries in stateColoradohave an average population of78581.1875
Countries in stateConnecticuthave an average population of446762.125
Countries in stateDelawarehave an average population of299311.3333333333
Countries in stateDistrict of Columbiahave an average population of601723.0
Countries in stateFloridahave an average population of280616.5671641791
Countries in stateGeorgiahave an average population of60928.63522012578
Countries in stateHawaiihave an average population of272060.2
Countries in stateIdahohave an average population of35626.86363636364
Countries in stateIllinoishave an average population of125790.50980392157
Countries in stateIndianahave an average population of70476.10869565218
Countries in stateIowahave an average population of30771.262626262625
Countries in stateKansashave an average population of27172.55238095238
Countries in stateKentuckyhave an average population of36161.39166666667
Countries in stateLouisianahave an average population of70833.9375
Countries in stateMainehave an average population of83022.5625
Countries in stateMarylandhave an average population of240564.66666666666
Countries in stateMassachusettshave an average population of467687.78571428574
Countries in stateMichiganhave an average population of119080.0
Countries in stateMinnesotahave an average population of60964.65517241379
Countries in stateMississippihave an average population of36186.54878048781
Countries in stateMissourihave an average population of52077.62608695652
Countries in stateMontanahave an average population of17668.125
Countries in stateNebraskahave an average population of19638.075268817203
Countries in stateNevadahave an average population of158855.9411764706
Countries in stateNew Hampshirehave an average population of131647.0
Countries in stateNew Jerseyhave an average population of418661.61904761905
Countries in stateNew Mexicohave an average population of62399.36363636364
Countries in stateNew Yorkhave an average population of312550.03225806454
Countries in stateNorth Carolinahave an average population of95354.83
Countries in stateNorth Dakotahave an average population of12690.396226415094
Countries in stateOhiohave an average population of131096.63636363635
Countries in stateOklahomahave an average population of48718.844155844155
Countries in stateOregonhave an average population of106418.72222222222
Countries in statePennsylvaniahave an average population of189587.74626865672
Countries in stateRhode Islandhave an average population of210513.4
Countries in stateSouth Carolinahave an average population of100551.39130434782
Countries in stateSouth Dakotahave an average population of12336.060606060606
Countries in stateTennesseehave an average population of66801.1052631579
Countries in stateTexashave an average population of98998.27165354331

Countries in stateUtahhave an average population of95306.37931034483
Countries in stateVermonthave an average population of44695.78571428572
Countries in stateVirginiahave an average population of60111.29323308271
Countries in stateWashingtonhave an average population of172424.10256410256
Countries in stateWest Virginiahave an average population of33690.8
Countries in stateWisconsinhave an average population of78985.91666666667
Countries in stateWyominghave an average population of24505.478260869564
2.41 s ± 81.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [12]:
df.groupby('STNAME').head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861
5,50,3,6,1,9,Alabama,Blount County,57322,57322,57373,...,1.807375,-1.177622,-1.748766,-2.062535,-1.369970,1.859511,-0.848580,-1.402476,-1.577232,-0.884411
69,50,4,9,2,13,Alaska,Aleutians East Borough,3141,3141,3169,...,-5.604858,-12.221204,-17.257039,-27.748454,-16.221087,19.305620,8.249313,5.752346,-3.920977,7.509763
70,50,4,9,2,16,Alaska,Aleutians West Census Area,5561,5561,5546,...,-11.496318,0.000000,-13.711875,-11.179039,-26.717891,1.257410,13.314397,0.175793,4.890830,-10.826858
71,50,4,9,2,20,Alaska,Anchorage Municipality,291826,291826,293405,...,-3.788123,-7.563712,-3.962343,-18.897015,-19.781254,-0.969922,-2.652342,0.053320,-14.789980,-15.280810
72,50,4,9,2,50,Alaska,Bethel Census Area,17013,17013,17080,...,0.057906,-3.926031,-9.731949,-13.525220,-14.441440,0.173717,-3.300142,-9.056901,-12.798659,-13.716580
73,50,4,9,2,60,Alaska,Bristol Bay Borough,997,997,1002,...,23.529412,-54.401583,-33.023736,-14.736842,-55.495103,23.529412,-54.401583,-33.023736,-14.736842,-55.495103
99,50,4,8,4,1,Arizona,Apache County,71518,71518,71766,...,1.775891,1.197250,-20.566049,-5.674114,-11.302431,2.094996,1.500003,-20.220982,-5.326435,-10.939637
100,50,4,8,4,3,Arizona,Cochise County,131346,131357,131809,...,3.353411,-15.621933,-22.883978,-23.290753,-13.596166,5.128302,-12.065659,-20.574165,-20.939882,-10.798115
101,50,4,8,4,5,Arizona,Coconino County,134421,134437,134626,...,-12.402905,4.908203,-3.154921,-0.809483,2.992043,-11.569596,5.818774,-2.120401,0.444851,4.256795
102,50,4,8,4,7,Arizona,Gila County,53597,53597,53544,...,-0.766233,-6.628859,-0.056574,4.125692,1.712168,-0.429838,-6.234508,0.396017,4.615501,2.220173
103,50,4,8,4,9,Arizona,Graham County,37220,37220,37137,...,-9.054407,-10.941954,3.659258,5.972606,-17.348990,-8.946617,-10.860902,3.793790,6.264600,-17.031630
115,50,3,7,5,1,Arkansas,Arkansas County,19019,19018,19014,...,-6.544054,2.799271,-10.483124,-15.687324,-7.460064,-5.488561,3.802783,-9.424222,-14.455896,-6.216720
116,50,3,7,5,3,Arkansas,Ashley County,21853,21853,21831,...,-8.785244,-9.410783,-11.842074,-14.846789,-4.453596,-8.831241,-9.457142,-11.888881,-14.846789,-4.453596
117,50,3,7,5,5,Arkansas,Baxter County,41513,41513,41538,...,2.101170,3.230547,4.851824,5.280722,10.696624,2.125322,3.279127,4.900586,5.329617,10.745467
118,50,3,7,5,7,Arkansas,Benton County,221339,221344,223010,...,11.164115,11.786353,9.333699,11.268649,16.254517,13.816535,14.533319,12.296171,14.648828,19.555772
119,50,3,7,5,9,Arkansas,Boone County,36903,36903,36897,...,4.003138,6.050583,0.642441,-6.520077,0.510931,3.976089,5.889234,0.535368,-6.627403,0.430258
191,50,4,9,6,1,California,Alameda County,1510271,1510261,1513754,...,-0.363660,2.488670,3.743636,4.436457,2.141452,6.535369,9.157917,10.954544,12.487898,10.059473
192,50,4,9,6,3,California,Alpine County,1175,1175,1159,...,-47.577093,11.622709,15.859031,-32.874278,6.314840,-46.696035,12.516764,16.740088,-31.985784,7.216960
193,50,4,9,6,5,California,Amador County,38091,38091,37873,...,-3.766029,-8.440854,-9.743520,7.254381,10.034579,-3.527337,-8.065705,-9.254987,7.772551,10.549868
194,50,4,9,6,7,California,Butte County,220000,220000,219977,...,-1.213647,3.934509,2.711121,6.306773,3.043761,-0.454550,4.782151,3.608814,7.431862,4.205196
195,50,4,9,6,9,California,Calaveras County,45578,45578,45464,...,-6.050903,-6.054131,0.604507,3.679234,8.612686,-5.653398,-5.720264,1.052290,4.150355,9.082469
250,50,4,8,8,1,Colorado,Adams County,441603,441687,443680,...,5.982917,7.689510,9.494072,10.849385,10.003023,7.605895,9.334759,11.312999,12.975974,12.150054
251,50,4,8,8,3,Colorado,Alamosa County,15445,15445,15926,...,5.490906,-5.517156,2.592433,-5.340044,1.706589,6.114872,-4.711279,3.580026,-4.296587,2.742732
252,50,4,8,8,5,Colorado,Arapahoe County,572003,572155,574727,...,7.756987,6.256681,8.577457,6.718039,7.128637,11.252972,10.087820,12.627969,11.245590,11.633206
253,50,4,8,8,7,Colorado,Archuleta County,12084,12084,12056,...,-9.640156,4.974299,6.091036,0.573912,10.911164,-9.307737,5.223014,6.420282,0.983848,11.318297
254,50,4,8,8,9,Colorado,Baca County,3788,3788,3790,...,8.684211,-7.922884,-16.924110,-14.486812,-0.551724,8.947368,-7.658788,-16.655473,-13.666803,0.275862
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2852,50,1,1,50,1,Vermont,Addison County,36821,36824,36820,...,-0.705630,-1.437776,-1.328417,0.838348,-3.807209,0.949887,0.352662,0.840427,3.245217,-1.377076
2853,50,1,1,50,3,Vermont,Bennington County,37125,37125,37105,...,-3.868106,-2.203572,1.090186,-4.842019,-0.549987,-3.435311,-1.795503,1.526260,-4.294898,0.000000
2854,50,1,1,50,5,Vermont,Caledonia County,31227,31232,31181,...,-1.990114,-0.739348,1.735999,-5.413854,-6.059526,-1.572832,-0.450038,2.057481,-5.059375,-5.670679
2855,50,1,1,50,7,Vermont,Chittenden County,156545,156540,156805,...,-0.044508,-0.031596,0.451860,-1.652769,-3.669383,2.549666,2.932088,3.577223,1.927191,-0.068296
2856,50,1,1,50,9,Vermont,Essex County,6306,6306,6302,...,1.425178,-15.297586,-2.416432,-10.713416,6.833713,1.425178,-15.297586,-2.255336,-10.551092,6.996420
2867,50,3,5,51,1,Virginia,Accomack County,33164,33164,33165,...,1.625233,-2.312278,-9.650326,-0.090905,-1.606767,3.280563,-0.030030,-7.659947,2.212021,0.848858
2868,50,3,5,51,3,Virginia,Albemarle County,98970,98998,99236,...,5.393263,6.682955,2.841173,6.466120,6.426919,8.415091,9.960268,6.268154,10.384396,10.330677
2869,50,3,5,51,5,Virginia,Alleghany County,16250,16261,16211,...,6.267089,-3.008627,2.898729,-10.910565,-5.386395,6.451415,-2.947226,3.022080,-10.785872,-5.259656
2870,50,3,5,51,7,Virginia,Amelia County,12690,12695,12742,...,-2.117730,-1.098168,-1.729696,4.473571,9.576456,-0.392172,-0.549084,-1.179338,5.101440,10.199315
2871,50,3,5,51,9,Virginia,Amherst County,32353,32354,32385,...,-7.658440,10.655433,-6.280260,-3.423592,-3.094911,-7.596428,10.841284,-6.063700,-3.205727,-2.844817
3001,50,4,9,53,1,Washington,Adams County,18728,18728,18810,...,-14.962990,-12.524772,-6.093077,-10.807142,-12.120266,-13.901785,-11.943454,-5.305179,-9.397515,-10.507699
3002,50,4,9,53,3,Washington,Asotin County,21623,21623,21710,...,8.480403,-1.095940,11.230336,2.799223,-2.618924,8.342883,-1.324261,11.003001,2.573480,-2.844693
3003,50,4,9,53,5,Washington,Benton County,175177,175177,176516,...,14.001837,1.955320,2.587738,2.672191,10.239922,15.256402,3.183591,3.987840,4.234560,11.789174
3004,50,4,9,53,7,Washington,Chelan County,72453,72456,72743,...,2.628877,0.666522,-0.324838,3.121237,8.413094,3.587321,1.618695,0.812095,4.480052,9.784215
3005,50,4,9,53,9,Washington,Clallam County,71404,71404,71533,...,6.280048,3.899531,7.330737,8.282145,13.533670,6.838275,4.665511,8.038820,9.041342,14.395774
3041,50,3,5,54,1,West Virginia,Barbour County,16589,16589,16596,...,1.265251,14.046623,-2.972475,-1.493028,2.274632,1.385751,14.046623,-2.972475,-1.373585,2.394349
3042,50,3,5,54,3,West Virginia,Berkeley County,104169,104172,104646,...,4.906062,7.784296,8.403712,11.389012,8.385254,5.600137,8.574007,9.127210,12.220127,9.203986
3043,50,3,5,54,5,West Virginia,Boone County,24629,24627,24585,...,-3.997471,-1.556835,-10.980845,-12.925896,-13.713752,-4.038262,-1.597804,-11.022127,-12.967727,-13.756209
3044,50,3,5,54,7,West Virginia,Braxton County,14523,14519,14527,...,-0.275198,-2.342404,-2.489368,2.077347,-0.692953,-0.068799,-2.135722,-2.212772,2.354326,-0.415772
3045,50,3,5,54,9,West Virginia,Brooke County,24069,24071,24007,...,2.920439,1.340735,1.010186,-2.878855,-1.237228,3.003880,1.466429,1.220641,-2.667175,-1.023913
3097,50,2,3,55,1,Wisconsin,Adams County,20875,20875,20864,...,7.469833,-13.276686,5.510985,-8.701851,2.726687,7.517717,-13.131850,5.754834,-8.357710,3.172872
3098,50,2,3,55,3,Wisconsin,Ashland County,16157,16157,16163,...,-5.210110,-12.316734,8.634714,2.427411,-12.782355,-5.086060,-12.191691,8.759855,2.551894,-12.657038
3099,50,2,3,55,5,Wisconsin,Barron County,45870,45870,45840,...,1.024523,-4.928472,-4.811057,-4.585495,-0.614939,1.504087,-3.859909,-3.630161,-3.225205,0.746711
3100,50,2,3,55,7,Wisconsin,Bayfield County,15014,15014,15011,...,7.172029,-0.927152,4.370282,-8.911352,2.805518,7.636883,-0.463576,4.833797,-8.379331,3.339902
3101,50,2,3,55,9,Wisconsin,Brown County,248007,248007,248507,...,0.965796,2.073066,-1.630833,-0.355980,-0.624871,2.372413,3.606022,-0.003939,1.607777,1.319604
3170,50,4,8,56,1,Wyoming,Albany County,36299,36299,36428,...,3.708956,2.637812,-3.544634,-3.334877,-9.911169,6.736119,6.433032,0.719587,1.429233,-5.166460
3171,50,4,8,56,3,Wyoming,Big Horn County,11668,11668,11672,...,4.868258,2.804930,16.815908,-8.026420,5.095861,4.868258,3.144921,17.236306,-7.608378,5.513554
3172,50,4,8,56,5,Wyoming,Campbell County,46133,46133,46244,...,-2.843479,15.601020,-5.895711,-8.550911,10.916963,-2.649606,15.558684,-5.916543,-8.509402,10.978525
3173,50,4,8,56,7,Wyoming,Carbon County,15885,15885,15837,...,-7.581980,-13.081441,3.178134,-2.970641,-23.300971,-7.392431,-12.636926,3.623073,-2.338590,-22.600668
3174,50,4,8,56,9,Wyoming,Converse County,13833,13833,13826,...,-12.847499,15.493820,19.035533,-20.550587,-0.070403,-12.774915,16.502720,20.093063,-19.358233,1.126443

In [15]:
for group,frame in df.groupby('STNAME'):
    print(frame['CENSUS2010POP'])

1      54571
2     182265
3      27457
4      22915
5      57322
6      10914
7      20947
8     118572
9      34215
10     25989
11     43643
12     13859
13     25833
14     13932
15     14972
16     49948
17     54428
18     13228
19     11539
20     37765
21     13906
22     80406
23     50251
24     43820
25     71109
26     79303
27     38319
28    104430
29     17241
30     31704
       ...
38     14564
39     92709
40     34339
41    140247
42     82782
43     11299
44     21452
45    334811
46     21027
47     30776
48     93019
49    412992
50     23068
51    229363
52    119490
53     10591
54     19746
55     32899
56     22913
57     52947
58     83593
59    195085
60     13763
61     82291
62     41616
63    194656
64     67023
65     17581
66     11670
67     24484
Name: CENSUS2010POP, Length: 67, dtype: int64
69      3141
70      5561
71    291826
72     17013
73       997
74      1826
75      4847
76     97581
77      2508
78      2150
79     31275
80     55400
81     13477
82     13592
83      7459
84      1631
85     88995
86      9492
87      9430
88      7523
89      3815
90      5559
91      8881
92       968
93      7029
94      9636
95      2369
96       662
97      5588
Name: CENSUS2010POP, dtype: int64
99       71518
100     131346
101     134421
102      53597
103      37220
104       8437
105      20489
106    3817117
107     200186
108     107449
109     980263
110     375770
111      47420
112     211033
113     195751
Name: CENSUS2010POP, dtype: int64
115     19019
116     21853
117     41513
118    221339
119     36903
120     11508
121      5368
122     27446
123     11800
124     22995
125     16083
126     25970
127      8689
128     24552
129     21273
130     96443
131     61948
132     50902
133     17870
134      8116
135     13008
136     18509
137    113237
138     18125
139     12245
140     96024
141     17853
142     42090
143     22609
144     32923
        ...
160     43462
161     46480
162      8149
163      9487
164      8997
165      8330
166     26120
167     10445
168     21757
169     11291
170     24583
171     20662
172     61754
173      8715
174    382748
175     17969
176     28258
177    107118
178     11233
179      8195
180    125744
181     17058
182     17264
183     12394
184     41639
185     17295
186    203065
187     77076
188      7260
189     22185
Name: CENSUS2010POP, Length: 75, dtype: int64
191    1510271
192       1175
193      38091
194     220000
195      45578
196      21419
197    1049025
198      28610
199     181058
200     930450
201      28122
202     134623
203     174528
204      18546
205     839631
206     152982
207      64665
208      34895
209    9818605
210     150865
211     252409
212      18251
213      87841
214     255793
215       9686
216      14202
217     415057
218     136484
219      98764
220    3010232
221     348432
222      20007
223    2189641
224    1418788
225      55269
226    2035210
227    3095313
228     805235
229     685306
230     269637
231     718451
232     423895
233    1781642
234     262382
235     177223
236       3240
237      44900
238     413344
239     483878
240     514453
241      94737
242      63463
243      13786
244     442179
245      55365
246     823318
247     200849
248      72155
Name: CENSUS2010POP, dtype: int64
250    441603
251     15445
252    572003
253     12084
254      3788
255      6499
256    294567
257     55889
258     17809
259      1836
260      9088
261      8256
262      3524
263      5823
264      4255
265     30952
266    600158
267      2064
268    285465
269     52197
270     23086
271    622263
272     46824
273     56389
274      5441
275     14843
276     15324
277       843
278      6711
279      1394
        ...
284     51334
285    299630
286     15507
287      5467
288     22709
289    146723
290       712
291     13795
292     25535
293     41276
294     28159
295     18831
296      4436
297     16206
298      4442
299     17148
300     12551
301    159063
302      6666
303     11982
304     23509
305      6108
306       699
307      7359
308      2379
309     27994
310     23350
311      4814
312    252825
313     10043
Name: CENSUS2010POP, Length: 64, dtype: int64
315    916829
316    894014
317    189927
318    165676
319    862477
320    274055
321    152691
322    118428
Name: CENSUS2010POP, dtype: int64
324    162310
325    538479
326    197145
Name: CENSUS2010POP, dtype: int64
328    601723
Name: CENSUS2010POP, dtype: int64
330     247336
331      27115
332     168852
333      28520
334     543376
335    1748066
336      14625
337     159978
338     141236
339     190865
340     321520
341      67531
342      34862
343      16422
344     864263
345     297619
346      95696
347      11549
348      46389
349      16939
350      12884
351      15863
352      14799
353      27731
354      39140
355     172778
356      98786
357    1229226
358      19927
359     138028
        ...
367       8365
368      19224
369     322833
370     331298
371     146318
372    2496435
373      73090
374      73314
375     180822
376      39996
377    1145956
378     268685
379    1320134
380     464697
381     916542
382     602095
383      74364
384     190039
385     277789
386     151372
387     379448
388     422718
389      93420
390      41551
391      22570
392      15535
393     494593
394      30776
395      55043
396      24896
Name: CENSUS2010POP, Length: 67, dtype: int64
398     18236
399      8375
400     11096
401      3451
402     45720
403     18395
404     69367
405    100157
406     17634
407     19286
408    155547
409     13063
410     18411
411     16243
412     30233
413     70217
414     23316
415     23655
416      6694
417     50513
418     10998
419    110527
420     63942
421     12171
422    265128
423     11267
424     26015
425    214346
426    116714
427      3183
        ...
527      6865
528      1717
529     25520
530      8906
531     16500
532      9315
533     44720
534     40118
535     27223
536     10471
537      6885
538     67044
539      8930
540      9023
541     21356
542     27153
543     68756
544     83768
545     36312
546      5834
547     21187
548     30099
549      2799
550      7421
551     27144
552    102599
553      9255
554     10593
555      9563
556     21679
Name: CENSUS2010POP, Length: 159, dtype: int64
558    185079
559    953207
560        90
561     67091
562    154834
Name: CENSUS2010POP, dtype: int64
564    392365
565      3976
566     82839
567      5986
568      9285
569     45607
570     21376
571      7028
572     40877
573    104234
574     10972
575      2891
576      1117
577    188923
578      6963
579     22952
580       982
581      8761
582      4368
583     27038
584     12786
585     13242
586     16719
587     15464
588     16267
589     26140
590     22374
591    138494
592     37244
593      7936
594      3821
595      5208
596     37536
597     20069
598     39265
599      4286
600     11526
601     22623
602      7817
603     12765
604     10170
605     77230
606      9862
607     10198
Name: CENSUS2010POP, dtype: int64
609      67103
610       8238
611      17768
612      54165
613       6937
614      34978
615       5089
616      15387
617      13642
618     201081
619      34800
620      16335
621      13815
622      37762
623      53873
624    5194675
625      19817
626      11048
627     105160
628      16561
629      19980
630     916924
631      18576
632       6721
633      34242
634      22140
635      14081
636      39561
637      37069
638       5589
        ...
681      22350
682      16729
683      16430
684       4470
685       6161
686       6006
687      33476
688      16233
689     147546
690     270056
691      24913
692     197465
693       7544
694       5355
695      22363
696       5994
697      47711
698     135394
699      17808
700      81625
701      11947
702      17707
703      14716
704      16760
705      14665
706      58498
707     677560
708      66357
709     295266
710      38664
Name: CENSUS2010POP, Length: 102, dtype: int64
712     34387
713    355329
714     76794
715      8854
716     12766
717     56640
718     15242
719     20155
720     38966
721    110232
722     26890
723     33224
724     10713
725     31648
726     50047
727     25740
728     42223
729    117671
730     41889
731    197559
732     24277
733     74578
734     17240
735     23087
736     20836
737     33503
738     70061
739     33165
740    274569
741     70002
        ...
774     12845
775    164343
776     25910
777     13402
778     37963
779     26171
780     28818
781     17392
782    266931
783     24181
784     44436
785     20952
786     23363
787     34185
788     21475
789     10613
790    172780
791     15936
792      7516
793    179703
794     16212
795    107848
796     32888
797      8508
798     59689
799     28262
800     68917
801     27636
802     24643
803     33292
Name: CENSUS2010POP, Length: 92, dtype: int64
805      7682
806      4029
807     14330
808     12887
809      6119
810     26076
811    131090
812     26306
813     24276
814     20958
815     20260
816     14867
817      9670
818     20816
819     13956
820     18499
821     44151
822     12072
823     12439
824      9286
825     16667
826     18129
827     49116
828     17096
829     66135
830      8753
831      8457
832     17764
833     40325
834     16667
        ...
874     42745
875     14398
876      6462
877     15932
878      9421
879     24986
880      7310
881    430640
882     93158
883     18914
884      5131
885     10350
886    165224
887     12167
888     33704
889     89542
890     17767
891      6317
892     12534
893      7570
894     35625
895     46225
896     21704
897      6403
898     38013
899     10866
900     21056
901    102172
902      7598
903     13229
Name: CENSUS2010POP, Length: 99, dtype: int64
905      13371
906       8102
907      16924
908       4861
909      27674
910      15173
911       9984
912      65880
913       2790
914       3669
915      21603
916       2726
917       2215
918       8535
919       9533
920       8601
921       1891
922      36311
923      39134
924       2961
925      19754
926       7945
927     110826
928       3037
929       2882
930      28452
931       6497
932      36776
933      33848
934      25992
         ...
980       9656
981       2519
982      64511
983       4980
984      10083
985      71115
986       5181
987       3307
988       6970
989      55606
990       4936
991     498365
992      22952
993     177934
994       2556
995       6010
996       3853
997       4437
998       2235
999       5724
1000     24132
1001      7900
1002      3001
1003      7053
1004      1485
1005      5799
1006      2234
1007      9409
1008      3309
1009    157505
Name: CENSUS2010POP, Length: 105, dtype: int64
1011     18656
1012     19956
1013     21421
1014      8249
1015     42173
1016     11591
1017     28691
1018    118811
1019     19985
1020     49542
1021     28432
1022      8488
1023     13878
1024     20059
1025     74319
1026     12690
1027     12984
1028     37191
1029     90336
1030      5104
1031     10811
1032     27720
1033     15955
1034     73955
1035     35613
1036     21730
1037     10272
1038      9315
1039      6856
1040     96656
         ...
1101      7135
1102     23842
1103     60316
1104     10841
1105      4755
1106     14877
1107     28712
1108     65024
1109     12613
1110     63063
1111      2282
1112     17056
1113     23333
1114     17565
1115     47173
1116     42074
1117     17327
1118     17061
1119     24512
1120     12460
1121     14339
1122      8809
1123     15007
1124    113792
1125     11717
1126     20813
1127     13621
1128     35637
1129      7355
1130     24939
Name: CENSUS2010POP, Length: 120, dtype: int64
1132     61773
1133     25764
1134    107215
1135     23421
1136     42073
1137     35654
1138     14353
1139    116979
1140    254969
1141    192768
1142     10132
1143      6839
1144     10407
1145     17195
1146     20822
1147     26656
1148    440171
1149      7759
1150     20267
1151     33984
1152     20767
1153     22309
1154     73240
1155     33387
1156     16274
1157    432552
1158     31594
1159    221578
1160     96318
1161     14890
         ...
1166     39566
1167    343829
1168    153720
1169     23042
1170     22802
1171    131613
1172      9091
1173     20725
1174     24233
1175     35897
1176     52780
1177     11203
1178     22102
1179     45924
1180     83384
1181     52160
1182     54650
1183    233740
1184    121097
1185      5252
1186    111860
1187     22721
1188     57999
1189     52334
1190     47168
1191     41207
1192     23788
1193     11604
1194     15625
1195     15313
Name: CENSUS2010POP, Length: 64, dtype: int64
1197    107702
1198     71870
1199    281674
1200     30768
1201     54418
1202    122151
1203     39736
1204     34457
1205     57833
1206    153923
1207     17535
1208     35293
1209     52228
1210     38786
1211     32856
1212    197131
Name: CENSUS2010POP, dtype: int64
1214     75087
1215    537656
1216    805029
1217     88737
1218     33066
1219    167134
1220    101108
1221    146551
1222     32618
1223    233385
1224     30097
1225    244826
1226    287085
1227     20197
1228    971777
1229    863420
1230     47798
1231    105151
1232     26470
1233     37782
1234    147430
1235     98733
1236     51454
1237    620961
Name: CENSUS2010POP, dtype: int64
1239     215888
1240     131219
1241     548285
1242      16535
1243     743159
1244      71372
1245     463490
1246     158080
1247    1503085
1248      10172
1249     670850
1250     494919
1251     722023
1252     798552
Name: CENSUS2010POP, dtype: int64
1254      10942
1255       9601
1256     111408
1257      29598
1258      23580
1259      15899
1260       8860
1261      59173
1262     107771
1263      17525
1264     156813
1265      45248
1266     136146
1267      52293
1268      25949
1269      26152
1270      38520
1271      30926
1272      75382
1273      14074
1274      37069
1275      26168
1276     107759
1277      32694
1278     425790
1279      25692
1280      16427
1281      86986
1282      42476
1283      46688
         ...
1307      42798
1308      24029
1309      83629
1310      14849
1311     152021
1312      63342
1313       9765
1314     172188
1315      48460
1316    1202362
1317      26570
1318      21699
1319       6780
1320      23528
1321       8640
1322      24164
1323     263801
1324      13376
1325      24449
1326     200169
1327     163040
1328      61295
1329      43114
1330       8485
1331      70648
1332      55729
1333      76258
1334     344791
1335    1820584
1336      32735
Name: CENSUS2010POP, Length: 83, dtype: int64
1338      16202
1339     330844
1340      32504
1341      44442
1342      38451
1343       5269
1344      64013
1345      25893
1346      35386
1347      91042
1348      28567
1349      12441
1350      53887
1351      58999
1352       8695
1353       5176
1354      11687
1355      62500
1356     398552
1357      20087
1358      36009
1359      14553
1360      20866
1361      31255
1362      46183
1363       6018
1364    1152425
1365      19027
1366      20428
1367      37816
         ...
1395      29750
1396       9596
1397      31600
1398      10995
1399     508640
1400       4089
1401      16059
1402      15730
1403      64142
1404       9687
1405      15629
1406     200226
1407     129928
1408      88499
1409      15226
1410     150642
1411      36576
1412       9726
1413       9783
1414      24895
1415       3558
1416      21676
1417      13843
1418      19136
1419     238136
1420      11211
1421       6576
1422      51461
1423     124700
1424      10438
Name: CENSUS2010POP, Length: 87, dtype: int64
1426     32297
1427     37057
1428     13131
1429     19564
1430      8729
1431     34145
1432     14962
1433     10597
1434     17392
1435      8547
1436      9604
1437     16732
1438     20634
1439     26151
1440     29449
1441     19568
1442    161252
1443     74934
1444      8118
1445     22578
1446     14400
1447     21906
1448     43929
1449    187105
1450    245285
1451     19198
1452      9375
1453      1406
1454     23401
1455    139668
         ...
1478     47671
1479     34707
1480     55834
1481     12250
1482     40404
1483     29957
1484     25276
1485      8223
1486    141617
1487     28264
1488      4916
1489     27503
1490     16491
1491     17786
1492     29450
1493     15378
1494     28886
1495     22232
1496     19593
1497     10778
1498     27134
1499     15443
1500     48773
1501     51137
1502     20747
1503     10253
1504      9878
1505     19198
1506     12678
1507     28065
Name: CENSUS2010POP, Length: 82, dtype: int64
1509     25607
1510     17291
1511      5685
1512     25529
1513     35597
1514     12402
1515     17049
1516     19056
1517     12363
1518    162642
1519     89201
1520     42794
1521      9424
1522     44332
1523     44002
1524     75674
1525      9295
1526      6265
1527     99478
1528     13982
1529      7831
1530     77422
1531      7139
1532    221939
1533     20743
1534     75990
1535     17601
1536     24696
1537      7883
1538     16777
         ...
1594      4979
1595     10167
1596     25414
1597     23494
1598      6696
1599     14100
1600    360485
1601      9805
1602     18145
1603     65359
1604    998954
1605     23370
1606      4431
1607      4843
1608     39191
1609      8441
1610      6373
1611     29968
1612     32202
1613      6714
1614     51675
1615     26008
1616     21159
1617     32513
1618     25195
1619     13521
1620     36202
1621      2171
1622     18815
1623    319294
Name: CENSUS2010POP, Length: 115, dtype: int64
1625      9246
1626     12865
1627      6491
1628      5612
1629     10078
1630      1160
1631     81327
1632      5813
1633     11699
1634      1751
1635      8966
1636      9298
1637      2890
1638     11586
1639     90928
1640     89513
1641      1206
1642     13399
1643       884
1644      3079
1645     16096
1646     11406
1647      2072
1648     28746
1649     63395
1650      2339
1651     19687
1652      1734
1653      7691
1654      1891
1655      4223
1656    109299
1657      4538
1658     15636
1659       494
1660      4253
1661      6153
1662      1743
1663      7027
1664      1179
1665     40212
1666      9746
1667     10425
1668      9233
1669     11413
1670      3384
1671     34200
1672      9117
1673      3651
1674      6073
1675      5324
1676       718
1677      7369
1678      2168
1679      1017
1680    147972
Name: CENSUS2010POP, dtype: int64
1682     31364
1683      6685
1684       460
1685       690
1686       478
1687      5505
1688     11308
1689      2099
1690      3145
1691     46102
1692      6858
1693      8395
1694     25241
1695      8852
1696      3966
1697      5713
1698      9998
1699      6542
1700     10515
1701      9139
1702     10939
1703     21006
1704      9182
1705     24326
1706      1941
1707      6000
1708     36691
1709    517110
1710      2008
1711      5890
         ...
1745      7248
1746      4500
1747     15740
1748      2773
1749      2970
1750      9188
1751      7266
1752     32237
1753      5406
1754     11055
1755      8363
1756      1526
1757     14200
1758    158840
1759     20780
1760     36970
1761     16750
1762      5469
1763      3152
1764      1311
1765      6129
1766      5228
1767       647
1768      6940
1769      4260
1770     20234
1771      9595
1772      3812
1773       818
1774     13665
Name: CENSUS2010POP, Length: 93, dtype: int64
1776      24877
1777    1951269
1778      46997
1779      48818
1780        783
1781       1987
1782      16528
1783       5775
1784       5345
1785      51980
1786       4772
1787      43946
1788       6753
1789       4010
1790     421407
1791      10030
1792      55274
Name: CENSUS2010POP, dtype: int64
1794     60088
1795     47818
1796     77117
1797     33055
1798     89118
1799    400721
1800    146445
1801    295223
1802    123143
1803     43742
Name: CENSUS2010POP, dtype: int64
1805    274549
1806    905116
1807    448734
1808    513657

In [10]:
%%timeit -n 1
for group,frame in df.groupby('STNAME'):
    avg= np.average(frame['CENSUS2010POP'])
    print('Counties in state'+group+ 'have an average population of'+str(avg))

Counties in stateAlabamahave an average population of71339.34328358209
Counties in stateAlaskahave an average population of24490.724137931036
Counties in stateArizonahave an average population of426134.4666666667
Counties in stateArkansashave an average population of38878.90666666667
Counties in stateCaliforniahave an average population of642309.5862068966
Counties in stateColoradohave an average population of78581.1875
Counties in stateConnecticuthave an average population of446762.125
Counties in stateDelawarehave an average population of299311.3333333333
Counties in stateDistrict of Columbiahave an average population of601723.0
Counties in stateFloridahave an average population of280616.5671641791
Counties in stateGeorgiahave an average population of60928.63522012578
Counties in stateHawaiihave an average population of272060.2
Counties in stateIdahohave an average population of35626.86363636364
Counties in stateIllinoishave an average population of125790.50980392157
Counties in stateIndianahave an average population of70476.10869565218
Counties in stateIowahave an average population of30771.262626262625
Counties in stateKansashave an average population of27172.55238095238
Counties in stateKentuckyhave an average population of36161.39166666667
Counties in stateLouisianahave an average population of70833.9375
Counties in stateMainehave an average population of83022.5625
Counties in stateMarylandhave an average population of240564.66666666666
Counties in stateMassachusettshave an average population of467687.78571428574
Counties in stateMichiganhave an average population of119080.0
Counties in stateMinnesotahave an average population of60964.65517241379
Counties in stateMississippihave an average population of36186.54878048781
Counties in stateMissourihave an average population of52077.62608695652
Counties in stateMontanahave an average population of17668.125
Counties in stateNebraskahave an average population of19638.075268817203
Counties in stateNevadahave an average population of158855.9411764706
Counties in stateNew Hampshirehave an average population of131647.0
Counties in stateNew Jerseyhave an average population of418661.61904761905
Counties in stateNew Mexicohave an average population of62399.36363636364
Counties in stateNew Yorkhave an average population of312550.03225806454
Counties in stateNorth Carolinahave an average population of95354.83
Counties in stateNorth Dakotahave an average population of12690.396226415094
Counties in stateOhiohave an average population of131096.63636363635
Counties in stateOklahomahave an average population of48718.844155844155
Counties in stateOregonhave an average population of106418.72222222222
Counties in statePennsylvaniahave an average population of189587.74626865672
Counties in stateRhode Islandhave an average population of210513.4
Counties in stateSouth Carolinahave an average population of100551.39130434782
Counties in stateSouth Dakotahave an average population of12336.060606060606
Counties in stateTennesseehave an average population of66801.1052631579
Counties in stateTexashave an average population of98998.27165354331
Counties in stateUtahhave an average population of95306.37931034483
Counties in stateVermonthave an average population of44695.78571428572
Counties in stateVirginiahave an average population of60111.29323308271
Counties in stateWashingtonhave an average population of172424.10256410256
Counties in stateWest Virginiahave an average population of33690.8
Counties in stateWisconsinhave an average population of78985.91666666667
Counties in stateWyominghave an average population of24505.478260869564
Counties in stateAlabamahave an average population of71339.34328358209
Counties in stateAlaskahave an average population of24490.724137931036
Counties in stateArizonahave an average population of426134.4666666667
Counties in stateArkansashave an average population of38878.90666666667
Counties in stateCaliforniahave an average population of642309.5862068966
Counties in stateColoradohave an average population of78581.1875
Counties in stateConnecticuthave an average population of446762.125
Counties in stateDelawarehave an average population of299311.3333333333
Counties in stateDistrict of Columbiahave an average population of601723.0
Counties in stateFloridahave an average population of280616.5671641791
Counties in stateGeorgiahave an average population of60928.63522012578
Counties in stateHawaiihave an average population of272060.2
Counties in stateIdahohave an average population of35626.86363636364
Counties in stateIllinoishave an average population of125790.50980392157
Counties in stateIndianahave an average population of70476.10869565218
Counties in stateIowahave an average population of30771.262626262625
Counties in stateKansashave an average population of27172.55238095238
Counties in stateKentuckyhave an average population of36161.39166666667
Counties in stateLouisianahave an average population of70833.9375
Counties in stateMainehave an average population of83022.5625
Counties in stateMarylandhave an average population of240564.66666666666
Counties in stateMassachusettshave an average population of467687.78571428574
Counties in stateMichiganhave an average population of119080.0
Counties in stateMinnesotahave an average population of60964.65517241379
Counties in stateMississippihave an average population of36186.54878048781
Counties in stateMissourihave an average population of52077.62608695652
Counties in stateMontanahave an average population of17668.125
Counties in stateNebraskahave an average population of19638.075268817203
Counties in stateNevadahave an average population of158855.9411764706
Counties in stateNew Hampshirehave an average population of131647.0
Counties in stateNew Jerseyhave an average population of418661.61904761905
Counties in stateNew Mexicohave an average population of62399.36363636364
Counties in stateNew Yorkhave an average population of312550.03225806454
Counties in stateNorth Carolinahave an average population of95354.83
Counties in stateNorth Dakotahave an average population of12690.396226415094
Counties in stateOhiohave an average population of131096.63636363635
Counties in stateOklahomahave an average population of48718.844155844155
Counties in stateOregonhave an average population of106418.72222222222
Counties in statePennsylvaniahave an average population of189587.74626865672
Counties in stateRhode Islandhave an average population of210513.4
Counties in stateSouth Carolinahave an average population of100551.39130434782
Counties in stateSouth Dakotahave an average population of12336.060606060606
Counties in stateTennesseehave an average population of66801.1052631579
Counties in stateTexashave an average population of98998.27165354331
Counties in stateUtahhave an average population of95306.37931034483
Counties in stateVermonthave an average population of44695.78571428572
Counties in stateVirginiahave an average population of60111.29323308271
Counties in stateWashingtonhave an average population of172424.10256410256
Counties in stateWest Virginiahave an average population of33690.8
Counties in stateWisconsinhave an average population of78985.91666666667
Counties in stateWyominghave an average population of24505.478260869564
Counties in stateAlabamahave an average population of71339.34328358209
Counties in stateAlaskahave an average population of24490.724137931036
Counties in stateArizonahave an average population of426134.4666666667
Counties in stateArkansashave an average population of38878.90666666667
Counties in stateCaliforniahave an average population of642309.5862068966
Counties in stateColoradohave an average population of78581.1875
Counties in stateConnecticuthave an average population of446762.125
Counties in stateDelawarehave an average population of299311.3333333333
Counties in stateDistrict of Columbiahave an average population of601723.0
Counties in stateFloridahave an average population of280616.5671641791
Counties in stateGeorgiahave an average population of60928.63522012578
Counties in stateHawaiihave an average population of272060.2
Counties in stateIdahohave an average population of35626.86363636364
Counties in stateIllinoishave an average population of125790.50980392157
Counties in stateIndianahave an average population of70476.10869565218
Counties in stateIowahave an average population of30771.262626262625
Counties in stateKansashave an average population of27172.55238095238
Counties in stateKentuckyhave an average population of36161.39166666667
Counties in stateLouisianahave an average population of70833.9375
Counties in stateMainehave an average population of83022.5625
Counties in stateMarylandhave an average population of240564.66666666666
Counties in stateMassachusettshave an average population of467687.78571428574
Counties in stateMichiganhave an average population of119080.0
Counties in stateMinnesotahave an average population of60964.65517241379
Counties in stateMississippihave an average population of36186.54878048781
Counties in stateMissourihave an average population of52077.62608695652
Counties in stateMontanahave an average population of17668.125
Counties in stateNebraskahave an average population of19638.075268817203
Counties in stateNevadahave an average population of158855.9411764706
Counties in stateNew Hampshirehave an average population of131647.0
Counties in stateNew Jerseyhave an average population of418661.61904761905
Counties in stateNew Mexicohave an average population of62399.36363636364
Counties in stateNew Yorkhave an average population of312550.03225806454
Counties in stateNorth Carolinahave an average population of95354.83
Counties in stateNorth Dakotahave an average population of12690.396226415094
Counties in stateOhiohave an average population of131096.63636363635
Counties in stateOklahomahave an average population of48718.844155844155
Counties in stateOregonhave an average population of106418.72222222222
Counties in statePennsylvaniahave an average population of189587.74626865672
Counties in stateRhode Islandhave an average population of210513.4
Counties in stateSouth Carolinahave an average population of100551.39130434782
Counties in stateSouth Dakotahave an average population of12336.060606060606
Counties in stateTennesseehave an average population of66801.1052631579
Counties in stateTexashave an average population of98998.27165354331
Counties in stateUtahhave an average population of95306.37931034483
Counties in stateVermonthave an average population of44695.78571428572
Counties in stateVirginiahave an average population of60111.29323308271
Counties in stateWashingtonhave an average population of172424.10256410256
Counties in stateWest Virginiahave an average population of33690.8
Counties in stateWisconsinhave an average population of78985.91666666667
Counties in stateWyominghave an average population of24505.478260869564
Counties in stateAlabamahave an average population of71339.34328358209
Counties in stateAlaskahave an average population of24490.724137931036
Counties in stateArizonahave an average population of426134.4666666667
Counties in stateArkansashave an average population of38878.90666666667
Counties in stateCaliforniahave an average population of642309.5862068966
Counties in stateColoradohave an average population of78581.1875
Counties in stateConnecticuthave an average population of446762.125
Counties in stateDelawarehave an average population of299311.3333333333
Counties in stateDistrict of Columbiahave an average population of601723.0
Counties in stateFloridahave an average population of280616.5671641791
Counties in stateGeorgiahave an average population of60928.63522012578
Counties in stateHawaiihave an average population of272060.2
Counties in stateIdahohave an average population of35626.86363636364
Counties in stateIllinoishave an average population of125790.50980392157
Counties in stateIndianahave an average population of70476.10869565218
Counties in stateIowahave an average population of30771.262626262625
Counties in stateKansashave an average population of27172.55238095238
Counties in stateKentuckyhave an average population of36161.39166666667
Counties in stateLouisianahave an average population of70833.9375
Counties in stateMainehave an average population of83022.5625
Counties in stateMarylandhave an average population of240564.66666666666
Counties in stateMassachusettshave an average population of467687.78571428574
Counties in stateMichiganhave an average population of119080.0
Counties in stateMinnesotahave an average population of60964.65517241379
Counties in stateMississippihave an average population of36186.54878048781
Counties in stateMissourihave an average population of52077.62608695652
Counties in stateMontanahave an average population of17668.125
Counties in stateNebraskahave an average population of19638.075268817203
Counties in stateNevadahave an average population of158855.9411764706
Counties in stateNew Hampshirehave an average population of131647.0
Counties in stateNew Jerseyhave an average population of418661.61904761905
Counties in stateNew Mexicohave an average population of62399.36363636364
Counties in stateNew Yorkhave an average population of312550.03225806454
Counties in stateNorth Carolinahave an average population of95354.83
Counties in stateNorth Dakotahave an average population of12690.396226415094
Counties in stateOhiohave an average population of131096.63636363635
Counties in stateOklahomahave an average population of48718.844155844155
Counties in stateOregonhave an average population of106418.72222222222
Counties in statePennsylvaniahave an average population of189587.74626865672
Counties in stateRhode Islandhave an average population of210513.4
Counties in stateSouth Carolinahave an average population of100551.39130434782
Counties in stateSouth Dakotahave an average population of12336.060606060606
Counties in stateTennesseehave an average population of66801.1052631579
Counties in stateTexashave an average population of98998.27165354331
Counties in stateUtahhave an average population of95306.37931034483
Counties in stateVermonthave an average population of44695.78571428572
Counties in stateVirginiahave an average population of60111.29323308271
Counties in stateWashingtonhave an average population of172424.10256410256
Counties in stateWest Virginiahave an average population of33690.8
Counties in stateWisconsinhave an average population of78985.91666666667
Counties in stateWyominghave an average population of24505.478260869564
Counties in stateAlabamahave an average population of71339.34328358209
Counties in stateAlaskahave an average population of24490.724137931036
Counties in stateArizonahave an average population of426134.4666666667
Counties in stateArkansashave an average population of38878.90666666667
Counties in stateCaliforniahave an average population of642309.5862068966
Counties in stateColoradohave an average population of78581.1875
Counties in stateConnecticuthave an average population of446762.125
Counties in stateDelawarehave an average population of299311.3333333333
Counties in stateDistrict of Columbiahave an average population of601723.0
Counties in stateFloridahave an average population of280616.5671641791
Counties in stateGeorgiahave an average population of60928.63522012578
Counties in stateHawaiihave an average population of272060.2
Counties in stateIdahohave an average population of35626.86363636364
Counties in stateIllinoishave an average population of125790.50980392157
Counties in stateIndianahave an average population of70476.10869565218
Counties in stateIowahave an average population of30771.262626262625
Counties in stateKansashave an average population of27172.55238095238
Counties in stateKentuckyhave an average population of36161.39166666667
Counties in stateLouisianahave an average population of70833.9375
Counties in stateMainehave an average population of83022.5625
Counties in stateMarylandhave an average population of240564.66666666666
Counties in stateMassachusettshave an average population of467687.78571428574
Counties in stateMichiganhave an average population of119080.0
Counties in stateMinnesotahave an average population of60964.65517241379
Counties in stateMississippihave an average population of36186.54878048781
Counties in stateMissourihave an average population of52077.62608695652
Counties in stateMontanahave an average population of17668.125
Counties in stateNebraskahave an average population of19638.075268817203
Counties in stateNevadahave an average population of158855.9411764706
Counties in stateNew Hampshirehave an average population of131647.0
Counties in stateNew Jerseyhave an average population of418661.61904761905
Counties in stateNew Mexicohave an average population of62399.36363636364
Counties in stateNew Yorkhave an average population of312550.03225806454
Counties in stateNorth Carolinahave an average population of95354.83
Counties in stateNorth Dakotahave an average population of12690.396226415094
Counties in stateOhiohave an average population of131096.63636363635
Counties in stateOklahomahave an average population of48718.844155844155
Counties in stateOregonhave an average population of106418.72222222222
Counties in statePennsylvaniahave an average population of189587.74626865672
Counties in stateRhode Islandhave an average population of210513.4
Counties in stateSouth Carolinahave an average population of100551.39130434782
Counties in stateSouth Dakotahave an average population of12336.060606060606
Counties in stateTennesseehave an average population of66801.1052631579
Counties in stateTexashave an average population of98998.27165354331
Counties in stateUtahhave an average population of95306.37931034483
Counties in stateVermonthave an average population of44695.78571428572
Counties in stateVirginiahave an average population of60111.29323308271
Counties in stateWashingtonhave an average population of172424.10256410256
Counties in stateWest Virginiahave an average population of33690.8
Counties in stateWisconsinhave an average population of78985.91666666667
Counties in stateWyominghave an average population of24505.478260869564

Counties in stateAlabamahave an average population of71339.34328358209
Counties in stateAlaskahave an average population of24490.724137931036
Counties in stateArizonahave an average population of426134.4666666667
Counties in stateArkansashave an average population of38878.90666666667
Counties in stateCaliforniahave an average population of642309.5862068966
Counties in stateColoradohave an average population of78581.1875
Counties in stateConnecticuthave an average population of446762.125
Counties in stateDelawarehave an average population of299311.3333333333
Counties in stateDistrict of Columbiahave an average population of601723.0
Counties in stateFloridahave an average population of280616.5671641791
Counties in stateGeorgiahave an average population of60928.63522012578
Counties in stateHawaiihave an average population of272060.2
Counties in stateIdahohave an average population of35626.86363636364
Counties in stateIllinoishave an average population of125790.50980392157
Counties in stateIndianahave an average population of70476.10869565218
Counties in stateIowahave an average population of30771.262626262625
Counties in stateKansashave an average population of27172.55238095238
Counties in stateKentuckyhave an average population of36161.39166666667
Counties in stateLouisianahave an average population of70833.9375
Counties in stateMainehave an average population of83022.5625
Counties in stateMarylandhave an average population of240564.66666666666
Counties in stateMassachusettshave an average population of467687.78571428574
Counties in stateMichiganhave an average population of119080.0
Counties in stateMinnesotahave an average population of60964.65517241379
Counties in stateMississippihave an average population of36186.54878048781
Counties in stateMissourihave an average population of52077.62608695652
Counties in stateMontanahave an average population of17668.125
Counties in stateNebraskahave an average population of19638.075268817203
Counties in stateNevadahave an average population of158855.9411764706
Counties in stateNew Hampshirehave an average population of131647.0
Counties in stateNew Jerseyhave an average population of418661.61904761905
Counties in stateNew Mexicohave an average population of62399.36363636364
Counties in stateNew Yorkhave an average population of312550.03225806454
Counties in stateNorth Carolinahave an average population of95354.83
Counties in stateNorth Dakotahave an average population of12690.396226415094
Counties in stateOhiohave an average population of131096.63636363635
Counties in stateOklahomahave an average population of48718.844155844155
Counties in stateOregonhave an average population of106418.72222222222
Counties in statePennsylvaniahave an average population of189587.74626865672
Counties in stateRhode Islandhave an average population of210513.4
Counties in stateSouth Carolinahave an average population of100551.39130434782
Counties in stateSouth Dakotahave an average population of12336.060606060606
Counties in stateTennesseehave an average population of66801.1052631579
Counties in stateTexashave an average population of98998.27165354331
Counties in stateUtahhave an average population of95306.37931034483
Counties in stateVermonthave an average population of44695.78571428572
Counties in stateVirginiahave an average population of60111.29323308271
Counties in stateWashingtonhave an average population of172424.10256410256
Counties in stateWest Virginiahave an average population of33690.8
Counties in stateWisconsinhave an average population of78985.91666666667
Counties in stateWyominghave an average population of24505.478260869564
Counties in stateAlabamahave an average population of71339.34328358209
Counties in stateAlaskahave an average population of24490.724137931036
Counties in stateArizonahave an average population of426134.4666666667
Counties in stateArkansashave an average population of38878.90666666667
Counties in stateCaliforniahave an average population of642309.5862068966
Counties in stateColoradohave an average population of78581.1875
Counties in stateConnecticuthave an average population of446762.125
Counties in stateDelawarehave an average population of299311.3333333333
Counties in stateDistrict of Columbiahave an average population of601723.0
Counties in stateFloridahave an average population of280616.5671641791
Counties in stateGeorgiahave an average population of60928.63522012578
Counties in stateHawaiihave an average population of272060.2
Counties in stateIdahohave an average population of35626.86363636364
Counties in stateIllinoishave an average population of125790.50980392157
Counties in stateIndianahave an average population of70476.10869565218
Counties in stateIowahave an average population of30771.262626262625
Counties in stateKansashave an average population of27172.55238095238
Counties in stateKentuckyhave an average population of36161.39166666667
Counties in stateLouisianahave an average population of70833.9375
Counties in stateMainehave an average population of83022.5625
Counties in stateMarylandhave an average population of240564.66666666666
Counties in stateMassachusettshave an average population of467687.78571428574
Counties in stateMichiganhave an average population of119080.0
Counties in stateMinnesotahave an average population of60964.65517241379
Counties in stateMississippihave an average population of36186.54878048781
Counties in stateMissourihave an average population of52077.62608695652
Counties in stateMontanahave an average population of17668.125
Counties in stateNebraskahave an average population of19638.075268817203
Counties in stateNevadahave an average population of158855.9411764706
Counties in stateNew Hampshirehave an average population of131647.0
Counties in stateNew Jerseyhave an average population of418661.61904761905
Counties in stateNew Mexicohave an average population of62399.36363636364
Counties in stateNew Yorkhave an average population of312550.03225806454
Counties in stateNorth Carolinahave an average population of95354.83
Counties in stateNorth Dakotahave an average population of12690.396226415094
Counties in stateOhiohave an average population of131096.63636363635
Counties in stateOklahomahave an average population of48718.844155844155
Counties in stateOregonhave an average population of106418.72222222222
Counties in statePennsylvaniahave an average population of189587.74626865672
Counties in stateRhode Islandhave an average population of210513.4
Counties in stateSouth Carolinahave an average population of100551.39130434782
Counties in stateSouth Dakotahave an average population of12336.060606060606
Counties in stateTennesseehave an average population of66801.1052631579
Counties in stateTexashave an average population of98998.27165354331
Counties in stateUtahhave an average population of95306.37931034483
Counties in stateVermonthave an average population of44695.78571428572
Counties in stateVirginiahave an average population of60111.29323308271
Counties in stateWashingtonhave an average population of172424.10256410256
Counties in stateWest Virginiahave an average population of33690.8
Counties in stateWisconsinhave an average population of78985.91666666667
Counties in stateWyominghave an average population of24505.478260869564
45.4 ms ± 17 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [17]:
df = df.set_index('STNAME')
df.head(2)

,SUMLEV,REGION,DIVISION,STATE,COUNTY,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,POPESTIMATE2011,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
STNAME,,,,,,,,,,,,,,,,,,,,,
Alabama,50,3,6,1,1,Autauga County,54571,54571,54660,55253,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
Alabama,50,3,6,1,3,Baldwin County,182265,182265,183193,186659,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499

In [20]:
def fun(item):
    if item[0]<'M':
        return 0
    if item[0]<'Q':
        return 1
    return 2
for group,frame in df.groupby(fun):
    print('There are ' + str(len(frame)) + ' records in group '+ str(group)+'for processing')

There are 1177 records in group 0for processing
There are 1134 records in group 1for processing
There are 831 records in group 2for processing

In [22]:
df = pd.read_csv('census.csv')
df=df[df['SUMLEV']==50]

In [27]:
df.groupby('STNAME').agg({'CENSUS2010POP':np.average})

                      CENSUS2010POP
STNAME
Alabama                71339.343284
Alaska                 24490.724138
Arizona               426134.466667
Arkansas               38878.906667
California            642309.586207
Colorado               78581.187500
Connecticut           446762.125000
Delaware              299311.333333
District of Columbia  601723.000000
Florida               280616.567164
Georgia                60928.635220
Hawaii                272060.200000
Idaho                  35626.863636
Illinois              125790.509804
Indiana                70476.108696
Iowa                   30771.262626
Kansas                 27172.552381
Kentucky               36161.391667
Louisiana              70833.937500
Maine                  83022.562500
Maryland              240564.666667
Massachusetts         467687.785714
Michigan              119080.000000
Minnesota              60964.655172
Mississippi            36186.548780
Missouri               52077.626087
Montana                17668.125000
Nebraska               19638.075269
Nevada                158855.941176
New Hampshire         131647.000000
New Jersey            418661.619048
New Mexico             62399.363636
New York              312550.032258
North Carolina         95354.830000
North Dakota           12690.396226
Ohio                  131096.636364
Oklahoma               48718.844156
Oregon                106418.722222
Pennsylvania          189587.746269
Rhode Island          210513.400000
South Carolina        100551.391304
South Dakota           12336.060606
Tennessee              66801.105263
Texas                  98998.271654
Utah                   95306.379310
Vermont                44695.785714
Virginia               60111.293233
Washington            172424.102564
West Virginia          33690.800000
Wisconsin              78985.916667
Wyoming                24505.478261

In [36]:
df.groupby(level= 0)['POPESTIMATE2010','POPESTIMATE2011'].head()

      POPESTIMATE2010  POPESTIMATE2011
1               54660            55253
2              183193           186659
3               27341            27226
4               22861            22733
5               57373            57711
6               10887            10629
7               20944            20673
8              118437           117768
9               34098            33993
10              25976            26080
11              43665            43739
12              13841            13593
13              25767            25570
14              13880            13670
15              14973            14971
16              50177            50448
17              54514            54443
18              13208            13121
19              11758            11348
20              37796            38060
21              13853            13896
22              80473            80469
23              50358            50109
24              43803            43178
25              71142            71387
26              79465            80012
27              38309            38213
28             104442           104236
29              17231            17062
30              31734            31729
...               ...              ...
3162            15930            15784
3163           131967           132225
3164           390076           390808
3165            52422            52342
3166            24506            24581
3167           167059           167630
3168            74807            74647
3170            36428            36908
3171            11672            11745
3172            46244            46600
3173            15837            15817
3174            13826            13728
3175             7114             7129
3176            40222            40591
3177            13408            13597
3178             4813             4818
3179             8581             8636
3180            92271            92663
3181            18091            18022
3182            75472            76420
3183             2492             2485
3184            28259            28473
3185             8678             8701
3186            29146            29275
3187            10244            10142
3188            43593            44041
3189            21297            21482
3190            21102            20912
3191             8545             8469
3192             7181             7114

[3142 rows x 2 columns]

In [39]:
df.set_index('STNAME').groupby(level=0)['CENSUS2010POP'].agg({'avg':np.average,'sum':np.sum})

C:\Users\visha\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: using a dict on a Series for aggregation
is deprecated and will be removed in a future version
  """Entry point for launching an IPython kernel.

                                avg       sum
STNAME
Alabama                71339.343284   4779736
Alaska                 24490.724138    710231
Arizona               426134.466667   6392017
Arkansas               38878.906667   2915918
California            642309.586207  37253956
Colorado               78581.187500   5029196
Connecticut           446762.125000   3574097
Delaware              299311.333333    897934
District of Columbia  601723.000000    601723
Florida               280616.567164  18801310
Georgia                60928.635220   9687653
Hawaii                272060.200000   1360301
Idaho                  35626.863636   1567582
Illinois              125790.509804  12830632
Indiana                70476.108696   6483802
Iowa                   30771.262626   3046355
Kansas                 27172.552381   2853118
Kentucky               36161.391667   4339367
Louisiana              70833.937500   4533372
Maine                  83022.562500   1328361
Maryland              240564.666667   5773552
Massachusetts         467687.785714   6547629
Michigan              119080.000000   9883640
Minnesota              60964.655172   5303925
Mississippi            36186.548780   2967297
Missouri               52077.626087   5988927
Montana                17668.125000    989415
Nebraska               19638.075269   1826341
Nevada                158855.941176   2700551
New Hampshire         131647.000000   1316470
New Jersey            418661.619048   8791894
New Mexico             62399.363636   2059179
New York              312550.032258  19378102
North Carolina         95354.830000   9535483
North Dakota           12690.396226    672591
Ohio                  131096.636364  11536504
Oklahoma               48718.844156   3751351
Oregon                106418.722222   3831074
Pennsylvania          189587.746269  12702379
Rhode Island          210513.400000   1052567
South Carolina        100551.391304   4625364
South Dakota           12336.060606    814180
Tennessee              66801.105263   6346105
Texas                  98998.271654  25145561
Utah                   95306.379310   2763885
Vermont                44695.785714    625741
Virginia               60111.293233   7994802
Washington            172424.102564   6724540
West Virginia          33690.800000   1852994
Wisconsin              78985.916667   5686986
Wyoming                24505.478261    563626

In [40]:
(df.set_index('STNAME').groupby(level=0)['POPESTIMATE2010','POPESTIMATE2011']
    .agg({'avg': np.average, 'sum': np.sum}))

C:\Users\visha\Anaconda3\lib\site-packages\pandas\core\groupby\groupby.py:4658: FutureWarning: using a dict with renaming is deprecated and will be removed in a future version
  return super(DataFrameGroupBy, self).aggregate(arg, *args, **kwargs)

                                 avg                             sum  \
                     POPESTIMATE2010 POPESTIMATE2011 POPESTIMATE2010
STNAME
Alabama                 71420.313433    71658.328358         4785161
Alaska                  24621.413793    24921.379310          714021
Arizona                427213.866667   431248.800000         6408208
Arkansas                38965.253333    39180.506667         2922394
California             643691.017241   650000.586207        37334079
Colorado                78878.968750    79991.875000         5048254
Connecticut            447464.625000   448719.875000         3579717
Delaware               299930.333333   302638.666667          899791
District of Columbia   605126.000000   620472.000000          605126
Florida                281341.641791   285157.208955        18849890
Georgia                 61090.905660    61712.452830         9713454
Hawaii                 272796.000000   275645.400000         1363980
Idaho                   35704.227273    36003.045455         1570986
Illinois               125894.598039   126096.882353        12841249
Indiana                 70549.891304    70835.271739         6490590
Iowa                    30815.090909    30963.525253         3050694
Kansas                  27226.895238    27332.542857         2858824
Kentucky                36232.808333    36399.016667         4347937
Louisiana               71014.859375    71490.328125         4544951
Maine                   82980.937500    83016.062500         1327695
Maryland               241183.708333   243507.125000         5788409
Massachusetts          468931.142857   472271.214286         6565036
Michigan               119004.445783   118995.048193         9877369
Minnesota               61044.862069    61472.632184         5310903
Mississippi             36223.365854    36317.060976         2970316
Missouri                52139.582609    52265.973913         5996052
Montana                 17690.053571    17816.892857          990643
Nebraska                19677.688172    19810.569892         1830025
Nevada                 159025.882353   159930.529412         2703440
New Hampshire          131670.800000   131834.400000         1316708
New Jersey             419232.428571   421092.095238         8803881
New Mexico              62567.909091    62976.545455         2064741
New York               312950.322581   314890.354839        19402920
North Carolina          95589.790000    96510.250000         9558979
North Dakota            12726.981132    12930.679245          674530
Ohio                   131145.068182   131198.204545        11540766
Oklahoma                48825.922078    49176.961039         3759596
Oregon                 106610.333333   107458.583333         3837972
Pennsylvania           189731.552239   190226.895522        12712014
Rhode Island           210643.800000   210371.200000         1053219
South Carolina         100780.304348   101581.152174         4635894
South Dakota            12368.166667    12489.227273          816299
Tennessee               66911.421053    67351.663158         6356585
Texas                   99387.255906   101001.826772        25244363
Utah                    95704.344828    97118.620690         2775426
Vermont                 44713.142857    44763.357143          625984
Virginia                60344.263158    60983.330827         8025787
Washington             172898.974359   174954.589744         6743060
West Virginia           33713.181818    33726.327273         1854225
Wisconsin               79030.611111    79301.666667         5690204
Wyoming                 24544.173913    24685.565217          564516


                     POPESTIMATE2011
STNAME
Alabama                      4801108
Alaska                        722720
Arizona                      6468732
Arkansas                     2938538
California                  37700034
Colorado                     5119480
Connecticut                  3589759
Delaware                      907916
District of Columbia          620472
Florida                     19105533
Georgia                      9812280
Hawaii                       1378227
Idaho                        1584134
Illinois                    12861882
Indiana                      6516845
Iowa                         3065389
Kansas                       2869917
Kentucky                     4367882
Louisiana                    4575381
Maine                        1328257
Maryland                     5844171
Massachusetts                6611797
Michigan                     9876589
Minnesota                    5348119
Mississippi                  2977999
Missouri                     6010587
Montana                       997746
Nebraska                     1842383
Nevada                       2718819
New Hampshire                1318344
New Jersey                   8842934
New Mexico                   2078226
New York                    19523202
North Carolina               9651025
North Dakota                  685326
Ohio                        11545442
Oklahoma                     3786626
Oregon                       3868509
Pennsylvania                12745202
Rhode Island                 1051856
South Carolina               4672733
South Dakota                  824289
Tennessee                    6398408
Texas                       25654464
Utah                         2816440
Vermont                       626687
Virginia                     8110783
Washington                   6823229
West Virginia                1854948
Wisconsin                    5709720
Wyoming                       567768

In [41]:
df = pd.DataFrame(['A+', 'A', 'A-', 'B+', 'B', 'B-', 'C+', 'C', 'C-', 'D+', 'D'],
                  index=['excellent', 'excellent', 'excellent', 'good', 'good', 'good', 'ok', 'ok', 'ok', 'poor', 'poor'])
df.rename(columns={0: 'Grades'}, inplace=True)
df

          Grades
excellent     A+
excellent      A
excellent     A-
good          B+
good           B
good          B-
ok            C+
ok             C
ok            C-
poor          D+
poor           D

In [47]:
df['Grades'].astype('category').head()

excellent    A+
excellent     A
excellent    A-
good         B+
good          B
Name: Grades, dtype: category
Categories (11, object): [A, A+, A-, B, ..., C+, C-, D, D+]

In [48]:
df['Grades'].describe

<bound method NDFrame.describe of excellent    A+
excellent     A
excellent    A-
good         B+
good          B
good         B-
ok           C+
ok            C
ok           C-
poor         D+
poor          D
Name: Grades, dtype: object>

In [49]:
grades = df['Grades'].astype('category',
                             categories=['D', 'D+', 'C-', 'C', 'C+', 'B-', 'B', 'B+', 'A-', 'A', 'A+'],
                             ordered=True)
grades.head()

C:\Users\visha\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: specifying 'categories' or 'ordered' in .astype() is deprecated; pass a CategoricalDtype instead
  This is separate from the ipykernel package so we can avoid doing imports until

excellent    A+
excellent     A
excellent    A-
good         B+
good          B
Name: Grades, dtype: category
Categories (11, object): [D < D+ < C- < C ... B+ < A- < A < A+]

In [52]:
grades>'C'

excellent     True
excellent     True
excellent     True
good          True
good          True
good          True
ok            True
ok           False
ok           False
poor         False
poor         False
Name: Grades, dtype: bool

In [56]:
df = pd.read_csv('census.csv')
df = df[df['SUMLEV']==50]
df = df.set_index('STNAME').groupby(level=0)['CENSUS2010POP'].agg({'avg': np.average})
pd.cut(df['avg'],10)

C:\Users\visha\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: using a dict on a Series for aggregation
is deprecated and will be removed in a future version
  This is separate from the ipykernel package so we can avoid doing imports until

STNAME
Alabama                   (11706.087, 75333.413]
Alaska                    (11706.087, 75333.413]
Arizona                 (390320.176, 453317.529]
Arkansas                  (11706.087, 75333.413]
California              (579312.234, 642309.586]
Colorado                 (75333.413, 138330.766]
Connecticut             (390320.176, 453317.529]
Delaware                (264325.471, 327322.823]
District of Columbia    (579312.234, 642309.586]
Florida                 (264325.471, 327322.823]
Georgia                   (11706.087, 75333.413]
Hawaii                  (264325.471, 327322.823]
Idaho                     (11706.087, 75333.413]
Illinois                 (75333.413, 138330.766]
Indiana                   (11706.087, 75333.413]
Iowa                      (11706.087, 75333.413]
Kansas                    (11706.087, 75333.413]
Kentucky                  (11706.087, 75333.413]
Louisiana                 (11706.087, 75333.413]
Maine                    (75333.413, 138330.766]
Maryland                (201328.118, 264325.471]
Massachusetts           (453317.529, 516314.881]
Michigan                 (75333.413, 138330.766]
Minnesota                 (11706.087, 75333.413]
Mississippi               (11706.087, 75333.413]
Missouri                  (11706.087, 75333.413]
Montana                   (11706.087, 75333.413]
Nebraska                  (11706.087, 75333.413]
Nevada                  (138330.766, 201328.118]
New Hampshire            (75333.413, 138330.766]
New Jersey              (390320.176, 453317.529]
New Mexico                (11706.087, 75333.413]
New York                (264325.471, 327322.823]
North Carolina           (75333.413, 138330.766]
North Dakota              (11706.087, 75333.413]
Ohio                     (75333.413, 138330.766]
Oklahoma                  (11706.087, 75333.413]
Oregon                   (75333.413, 138330.766]
Pennsylvania            (138330.766, 201328.118]
Rhode Island            (201328.118, 264325.471]
South Carolina           (75333.413, 138330.766]
South Dakota              (11706.087, 75333.413]
Tennessee                 (11706.087, 75333.413]
Texas                    (75333.413, 138330.766]
Utah                     (75333.413, 138330.766]
Vermont                   (11706.087, 75333.413]
Virginia                  (11706.087, 75333.413]
Washington              (138330.766, 201328.118]
West Virginia             (11706.087, 75333.413]
Wisconsin                (75333.413, 138330.766]
Wyoming                   (11706.087, 75333.413]
Name: avg, dtype: category
Categories (10, interval[float64]): [(11706.087, 75333.413] < (75333.413, 138330.766] < (138330.766, 201328.118] < (201328.118, 264325.471] ... (390320.176, 453317.529] < (453317.529, 516314.881] < (516314.881, 579312.234] < (579312.234, 642309.586]]

In [58]:
pd.cut(df['avg'],2,labels=['small','big'])

STNAME
Alabama                 small
Alaska                  small
Arizona                   big
Arkansas                small
California                big
Colorado                small
Connecticut               big
Delaware                small
District of Columbia      big
Florida                 small
Georgia                 small
Hawaii                  small
Idaho                   small
Illinois                small
Indiana                 small
Iowa                    small
Kansas                  small
Kentucky                small
Louisiana               small
Maine                   small
Maryland                small
Massachusetts             big
Michigan                small
Minnesota               small
Mississippi             small
Missouri                small
Montana                 small
Nebraska                small
Nevada                  small
New Hampshire           small
New Jersey                big
New Mexico              small
New York                small
North Carolina          small
North Dakota            small
Ohio                    small
Oklahoma                small
Oregon                  small
Pennsylvania            small
Rhode Island            small
South Carolina          small
South Dakota            small
Tennessee               small
Texas                   small
Utah                    small
Vermont                 small
Virginia                small
Washington              small
West Virginia           small
Wisconsin               small
Wyoming                 small
Name: avg, dtype: category
Categories (2, object): [small < big]

In [60]:
df = pd.read_csv('cars.csv')
df.head()

,YEAR,Make,Model,Size,(kW),Unnamed: 5,TYPE,CITY (kWh/100 km),HWY (kWh/100 km),COMB (kWh/100 km),CITY (Le/100 km),HWY (Le/100 km),COMB (Le/100 km),(g/km),RATING,(km),TIME (h)
0,2012,MITSUBISHI,i-MiEV,SUBCOMPACT,49,A1,B,16.9,21.4,18.7,1.9,2.4,2.1,0,NaN,100,7
1,2012,NISSAN,LEAF,MID-SIZE,80,A1,B,19.3,23.0,21.1,2.2,2.6,2.4,0,NaN,117,7
2,2013,FORD,FOCUS ELECTRIC,COMPACT,107,A1,B,19.0,21.1,20.0,2.1,2.4,2.2,0,NaN,122,4
3,2013,MITSUBISHI,i-MiEV,SUBCOMPACT,49,A1,B,16.9,21.4,18.7,1.9,2.4,2.1,0,NaN,100,7
4,2013,NISSAN,LEAF,MID-SIZE,80,A1,B,19.3,23.0,21.1,2.2,2.6,2.4,0,NaN,117,7

In [64]:
df.pivot_table(values='(kW)',index= 'YEAR',columns= 'Make',aggfunc=np.mean)

Make    BMW  CHEVROLET   FORD   KIA  MITSUBISHI  NISSAN  SMART       TESLA
YEAR
2012    NaN        NaN    NaN   NaN        49.0    80.0    NaN         NaN
2013    NaN        NaN  107.0   NaN        49.0    80.0   35.0  280.000000
2014    NaN      104.0  107.0   NaN        49.0    80.0   35.0  268.333333
2015  125.0      104.0  107.0  81.0        49.0    80.0   35.0  320.666667
2016  125.0      104.0  107.0  81.0        49.0    80.0   35.0  409.700000

In [67]:
df.pivot_table(values='(kW)',index='YEAR',columns= 'Make',aggfunc=[np.mean,np.min],margins=True)

       mean                                                             \
Make    BMW CHEVROLET   FORD   KIA MITSUBISHI NISSAN SMART       TESLA
YEAR
2012    NaN       NaN    NaN   NaN       49.0   80.0   NaN         NaN
2013    NaN       NaN  107.0   NaN       49.0   80.0  35.0  280.000000
2014    NaN     104.0  107.0   NaN       49.0   80.0  35.0  268.333333
2015  125.0     104.0  107.0  81.0       49.0   80.0  35.0  320.666667
2016  125.0     104.0  107.0  81.0       49.0   80.0  35.0  409.700000
All   125.0     104.0  107.0  81.0       49.0   80.0  35.0  345.478261

                   amin                                                        \
Make         All    BMW CHEVROLET   FORD   KIA MITSUBISHI NISSAN SMART  TESLA
YEAR
2012   64.500000    NaN       NaN    NaN   NaN       49.0   80.0   NaN    NaN
2013  158.444444    NaN       NaN  107.0   NaN       49.0   80.0  35.0  270.0
2014  135.000000    NaN     104.0  107.0   NaN       49.0   80.0  35.0  225.0
2015  181.428571  125.0     104.0  107.0  81.0       49.0   80.0  35.0  280.0
2016  252.263158  125.0     104.0  107.0  81.0       49.0   80.0  35.0  283.0
All   190.622642  125.0     104.0  107.0  81.0       49.0   80.0  35.0  225.0


Make All
YEAR
2012  49
2013  35
2014  35
2015  35
2016  35
All   35

### Timesstamp

In [70]:
pd.Timestamp('9/1/2018 10:05AM')

Timestamp('2018-09-01 10:05:00')

In [71]:
pd.Period('1/2016')

Period('2016-01', 'M')

In [72]:
pd.Period('1/9')

Period('0001-01-09', 'D')

In [73]:
pd.Period('30/09/2018')

Period('2018-09-30', 'D')

In [74]:
t1 = pd.Series(list('abc'),[pd.Timestamp('2016-09-1'),pd.Timestamp('2018-09-2'),pd.Timestamp('2018-09-3')])

In [75]:
t1

2016-09-01    a
2018-09-02    b
2018-09-03    c
dtype: object

In [77]:
type(t1.index)

pandas.core.indexes.datetimes.DatetimeIndex

In [78]:
t2 = pd.Series(list('def'),[pd.Period('2018-09'),pd.Period('2018-10'),pd.Period('2018-11')])

In [79]:
t2

2018-09    d
2018-10    e
2018-11    f
Freq: M, dtype: object

In [80]:
type(t2.index)

pandas.core.indexes.period.PeriodIndex

In [81]:
d1= ['2 June 2013','Aug 29,2013','2015-04-3','7/9/16']
t3= pd.DataFrame(np.random.randint(10,100,(4,2)),index=d1,columns=['a','b'])

In [84]:
t3

              a   b
2 June 2013  39  32
Aug 29,2013  31  59
2015-04-3    97  92
7/9/16       70  70

In [86]:
t3.index = pd.to_datetime(t3.index)

OutOfBoundsDatetime: Out of bounds nanosecond timestamp: 1-08-29 00:00:00

In [87]:
d1 = ['2 June 2013', 'Aug 29, 2014', '2015-06-26', '7/12/16']
ts3 = pd.DataFrame(np.random.randint(10, 100, (4,2)), index=d1, columns=list('ab'))
ts3

               a   b
2 June 2013   17  39
Aug 29, 2014  17  13
2015-06-26    40  33
7/12/16       11  78

In [88]:
ts3.index = pd.to_datetime(ts3.index)

In [89]:
ts3

             a   b
2013-06-02  17  39
2014-08-29  17  13
2015-06-26  40  33
2016-07-12  11  78

In [90]:
pd.Timestamp('9/3/2018')-pd.Timestamp('9/5/2018')

Timedelta('-2 days +00:00:00')